langs = ["English","Japanese_Romanji"];

wlist = new WordList();

deflang1 = 'English';
deflang2 = 'Japanese_Romanji';
wlist.setWord("AA2", "English", "dangerous");
wlist.setWord("AA2", "Japanese_Romanji", "abunai");
wlist.setWord("AA3", "English", "love");
wlist.setWord("AA3", "Japanese_Romanji", "ai");
wlist.setWord("AA4", "English", "opponent");
wlist.setWord("AA4", "Japanese_Romanji", "aite");
wlist.setWord("AA5", "English", "Devil");
wlist.setWord("AA5", "Japanese_Romanji", "akuma");
wlist.setWord("AA6", "English", "Thank you");
wlist.setWord("AA6", "Japanese_Romanji", "arigatou");
wlist.setWord("AA7", "English", "monster");
wlist.setWord("AA7", "Japanese_Romanji", "bakemono");
wlist.setWord("AA8", "English", "because");
wlist.setWord("AA8", "Japanese_Romanji", "dakara");
wlist.setWord("AA9", "English", "silent");
wlist.setWord("AA9", "Japanese_Romanji", "damaru");
wlist.setWord("AA10", "English", "to deceive");
wlist.setWord("AA10", "Japanese_Romanji", "damasu");
wlist.setWord("AA11", "English", "who");
wlist.setWord("AA11", "Japanese_Romanji", "dare");
wlist.setWord("AA12", "English", "where");
wlist.setWord("AA12", "Japanese_Romanji", "doko");
wlist.setWord("AA13", "English", "good luck");
wlist.setWord("AA13", "Japanese_Romanji", "ganbatte");
wlist.setWord("AA14", "English", "cheerful");
wlist.setWord("AA14", "Japanese_Romanji", "gengi");
wlist.setWord("AA15", "English", "yes");
wlist.setWord("AA15", "Japanese_Romanji", "hai");
wlist.setWord("AA16", "English", "quick");
wlist.setWord("AA16", "Japanese_Romanji", "hayai");
wlist.setWord("AA17", "English", "strange");
wlist.setWord("AA17", "Japanese_Romanji", "hen");
wlist.setWord("AA18", "English", "harsh");
wlist.setWord("AA18", "Japanese_Romanji", "hidoi");
wlist.setWord("AA19", "English", "princess");
wlist.setWord("AA19", "Japanese_Romanji", "hime");
wlist.setWord("AA20", "English", "good");
wlist.setWord("AA20", "Japanese_Romanji", "ii");
wlist.setWord("AA21", "English", "to go");
wlist.setWord("AA21", "Japanese_Romanji", "iku");
wlist.setWord("AA22", "English", "life");
wlist.setWord("AA22", "Japanese_Romanji", "inochi");
wlist.setWord("AA23", "English", "pain");
wlist.setWord("AA23", "Japanese_Romanji", "itai");
wlist.setWord("AA24", "English", "god");
wlist.setWord("AA24", "Japanese_Romanji", "kami");
wlist.setWord("AA25", "English", "boyfriend");
wlist.setWord("AA25", "Japanese_Romanji", "kareshi");
wlist.setWord("AA26", "English", "girlfriend");
wlist.setWord("AA26", "Japanese_Romanji", "kanojo");
wlist.setWord("AA27", "English", "cute");
wlist.setWord("AA27", "Japanese_Romanji", "kawaii");
wlist.setWord("AA28", "English", "but");
wlist.setWord("AA28", "Japanese_Romanji", "kedo");
wlist.setWord("AA29", "English", "injury");
wlist.setWord("AA29", "Japanese_Romanji", "kega");
wlist.setWord("AA30", "English", "police");
wlist.setWord("AA30", "Japanese_Romanji", "keisatsu");
wlist.setWord("AA31", "English", "heart");
wlist.setWord("AA31", "Japanese_Romanji", "kokoro");
wlist.setWord("AA32", "English", "to kill");
wlist.setWord("AA32", "Japanese_Romanji", "korosu");
wlist.setWord("AA33", "English", "afraid");
wlist.setWord("AA33", "Japanese_Romanji", "kowai");
wlist.setWord("AA34", "English", "to come");
wlist.setWord("AA34", "Japanese_Romanji", "kuru");
wlist.setWord("AA35", "English", "magic");
wlist.setWord("AA35", "Japanese_Romanji", "mahou");
wlist.setWord("AA36", "English", "to lose");
wlist.setWord("AA36", "Japanese_Romanji", "makeru");
wlist.setWord("AA37", "English", "to protect");
wlist.setWord("AA37", "Japanese_Romanji", "mamoru");
wlist.setWord("AA38", "English", "to wait");
wlist.setWord("AA38", "Japanese_Romanji", "matsu");
wlist.setWord("AA39", "English", "priestess");
wlist.setWord("AA39", "Japanese_Romanji", "miko");
wlist.setWord("AA40", "English", "everyone");
wlist.setWord("AA40", "Japanese_Romanji", "mina");
wlist.setWord("AA41", "English", "already");
wlist.setWord("AA41", "Japanese_Romanji", "mou");
wlist.setWord("AA42", "English", "what");
wlist.setWord("AA42", "Japanese_Romanji", "nani");
wlist.setWord("AA43", "English", "human");
wlist.setWord("AA43", "Japanese_Romanji", "ningen");
wlist.setWord("AA44", "English", "angry");
wlist.setWord("AA44", "Japanese_Romanji", "okoru");
wlist.setWord("AA45", "English", "please");
wlist.setWord("AA45", "Japanese_Romanji", "onegai");
wlist.setWord("AA46", "English", "Goodbye");
wlist.setWord("AA46", "Japanese_Romanji", "sayonara");
wlist.setWord("AA47", "English", "however");
wlist.setWord("AA47", "Japanese_Romanji", "shikashi");
wlist.setWord("AA48", "English", "to believe");
wlist.setWord("AA48", "Japanese_Romanji", "shinjiru");
wlist.setWord("AA49", "English", "to die");
wlist.setWord("AA49", "Japanese_Romanji", "shinu");
wlist.setWord("AA50", "English", "affection");
wlist.setWord("AA50", "Japanese_Romanji", "suki");
wlist.setWord("AA51", "English", "to do");
wlist.setWord("AA51", "Japanese_Romanji", "suru");
wlist.setWord("AA52", "English", "to aid");
wlist.setWord("AA52", "Japanese_Romanji", "tasukeru");
wlist.setWord("AA53", "English", "to battle");
wlist.setWord("AA53", "Japanese_Romanji", "tatkau");
wlist.setWord("AA54", "English", "enemy");
wlist.setWord("AA54", "Japanese_Romanji", "teki");
wlist.setWord("AA55", "English", "friend");
wlist.setWord("AA55", "Japanese_Romanji", "tomodachi");
wlist.setWord("AA56", "English", "fate");
wlist.setWord("AA56", "Japanese_Romanji", "unmei");
wlist.setWord("AA57", "English", "traitor");
wlist.setWord("AA57", "Japanese_Romanji", "uragirimono");
wlist.setWord("AA58", "English", "happy");
wlist.setWord("AA58", "Japanese_Romanji", "ursehii");
wlist.setWord("AA59", "English", "a lie");
wlist.setWord("AA59", "Japanese_Romanji", "uso");
wlist.setWord("AA60", "English", "to understand");
wlist.setWord("AA60", "Japanese_Romanji", "wakaru");
wlist.setWord("AA61", "English", "I/me");
wlist.setWord("AA61", "Japanese_Romanji", "watashi");
wlist.setWord("AA62", "English", "promise");
wlist.setWord("AA62", "Japanese_Romanji", "yakusoku");
wlist.setWord("AA63", "English", "to stop");
wlist.setWord("AA63", "Japanese_Romanji", "yameru");
wlist.setWord("AA64", "English", "dream");
wlist.setWord("AA64", "Japanese_Romanji", "yume");
wlist.setWord("AA65", "English", "always");
wlist.setWord("AA65", "Japanese_Romanji", "zutto");
