langs = ["Chinese_Pinyin","Chinese_Simplified","Chinese_traditional","English"];

wlist = new WordList();

deflang1 = 'English';
deflang2 = 'Chinese_Pinyin';
wlist.setWord("canada", "English", "Canada");
wlist.setWord("canada", "Chinese_Pinyin", "Jiānádà");
wlist.setWord("canada", "Chinese_Simplified", "加拿大");
wlist.setWord("canada", "Chinese_traditional", "加拿大");
wlist.setWord("usa", "English", "United States");
wlist.setWord("usa", "Chinese_Pinyin", "Měiguó");
wlist.setWord("usa", "Chinese_Simplified", "美国");
wlist.setWord("usa", "Chinese_traditional", "美國");
wlist.setWord("mexico", "English", "Mexico");
wlist.setWord("mexico", "Chinese_Pinyin", "Mòxīgē");
wlist.setWord("mexico", "Chinese_Simplified", "墨西哥");
wlist.setWord("mexico", "Chinese_traditional", "墨西哥");
wlist.setWord("guatemala", "English", "Guatemala");
wlist.setWord("guatemala", "Chinese_Pinyin", "Guādìmǎlā");
wlist.setWord("guatemala", "Chinese_Simplified", "瓜地马拉");
wlist.setWord("guatemala", "Chinese_traditional", "瓜地馬拉");
wlist.setWord("belize", "English", "Belize");
wlist.setWord("belize", "Chinese_Pinyin", "Bólìzī");
wlist.setWord("belize", "Chinese_Simplified", "伯利兹");
wlist.setWord("belize", "Chinese_traditional", "伯利茲");
wlist.setWord("honduras", "English", "Honduras");
wlist.setWord("honduras", "Chinese_Pinyin", "Hóngdūlāsī");
wlist.setWord("honduras", "Chinese_Simplified", "洪都拉斯");
wlist.setWord("honduras", "Chinese_traditional", "洪都拉斯");
wlist.setWord("elsalvador", "English", "El Salvador");
wlist.setWord("elsalvador", "Chinese_Pinyin", "Sà'Ěrwǎduō");
wlist.setWord("elsalvador", "Chinese_Simplified", "萨尔瓦多");
wlist.setWord("elsalvador", "Chinese_traditional", "薩爾瓦多");
wlist.setWord("nicaragua", "English", "Nicaragua");
wlist.setWord("nicaragua", "Chinese_Pinyin", "Níjiālāguā");
wlist.setWord("nicaragua", "Chinese_Simplified", "尼加拉瓜");
wlist.setWord("nicaragua", "Chinese_traditional", "尼加拉瓜");
wlist.setWord("costarica", "English", "Costa Rica");
wlist.setWord("costarica", "Chinese_Pinyin", "Gēsīdálíjiā");
wlist.setWord("costarica", "Chinese_Simplified", "哥斯达黎加");
wlist.setWord("costarica", "Chinese_traditional", "哥斯達黎加");
wlist.setWord("panama", "English", "Panama");
wlist.setWord("panama", "Chinese_Pinyin", "Bānámǎ");
wlist.setWord("panama", "Chinese_Simplified", "巴拿马");
wlist.setWord("panama", "Chinese_traditional", "巴拿馬");
wlist.setWord("cuba", "English", "Cuba");
wlist.setWord("cuba", "Chinese_Pinyin", "Gǔbā");
wlist.setWord("cuba", "Chinese_Simplified", "古巴");
wlist.setWord("cuba", "Chinese_traditional", "古巴");
wlist.setWord("jamaica", "English", "Jamaica");
wlist.setWord("jamaica", "Chinese_Pinyin", "Yámǎijiā");
wlist.setWord("jamaica", "Chinese_Simplified", "牙买加");
wlist.setWord("jamaica", "Chinese_traditional", "牙買加");
wlist.setWord("haiti", "English", "Haiti");
wlist.setWord("haiti", "Chinese_Pinyin", "Hǎidì");
wlist.setWord("haiti", "Chinese_Simplified", "海地");
wlist.setWord("haiti", "Chinese_traditional", "海地");
wlist.setWord("dominicanrepublic", "English", "Dominican Republic");
wlist.setWord("dominicanrepublic", "Chinese_Pinyin", "Duōmíngníjiā");
wlist.setWord("dominicanrepublic", "Chinese_Simplified", "多明尼加");
wlist.setWord("dominicanrepublic", "Chinese_traditional", "多明尼加");
wlist.setWord("puertorico", "English", "Puerto Rico");
wlist.setWord("puertorico", "Chinese_Pinyin", "Bōdiōlígè");
wlist.setWord("puertorico", "Chinese_Simplified", "波多黎各");
wlist.setWord("puertorico", "Chinese_traditional", "波多黎各");
wlist.setWord("bahamas", "English", "the Bahamas");
wlist.setWord("bahamas", "Chinese_Pinyin", "Bāhāmǎ");
wlist.setWord("bahamas", "Chinese_Simplified", "巴哈马");
wlist.setWord("bahamas", "Chinese_traditional", "巴哈馬");
