langs = ["Chinese_Pinyin","Chinese_Simplified","Chinese_Traditional","English"];

wlist = new WordList();

deflang1 = 'English';
deflang2 = 'Chinese_Simplified';
wlist.setWord("AA2", "English", "operating system");
wlist.setWord("AA2", "Chinese_Simplified", "操作系统");
wlist.setWord("AA2", "Chinese_Traditional", "操作系統");
wlist.setWord("AA2", "Chinese_Pinyin", " cāozuò xìtǒng");
wlist.setWord("AA3", "English", "disk");
wlist.setWord("AA3", "Chinese_Simplified", "磁盘");
wlist.setWord("AA3", "Chinese_Traditional", "磁盤");
wlist.setWord("AA3", "Chinese_Pinyin", " cípán");
wlist.setWord("AA4", "English", "printer");
wlist.setWord("AA4", "Chinese_Simplified", "打印机");
wlist.setWord("AA4", "Chinese_Traditional", "打印機");
wlist.setWord("AA4", "Chinese_Pinyin", " dǎyìn jī");
wlist.setWord("AA5", "English", "computer");
wlist.setWord("AA5", "Chinese_Simplified", "电脑");
wlist.setWord("AA5", "Chinese_Traditional", "電腦");
wlist.setWord("AA5", "Chinese_Pinyin", " diànnǎo");
wlist.setWord("AA6", "English", "programming language");
wlist.setWord("AA6", "Chinese_Simplified", "电脑语言");
wlist.setWord("AA6", "Chinese_Traditional", "電腦語言");
wlist.setWord("AA6", "Chinese_Pinyin", " diànnǎo yǔyán");
wlist.setWord("AA7", "English", "workstation");
wlist.setWord("AA7", "Chinese_Simplified", "工作站");
wlist.setWord("AA7", "Chinese_Traditional", "工作站");
wlist.setWord("AA7", "Chinese_Pinyin", " gōngzuò zhàn");
wlist.setWord("AA8", "English", "CD");
wlist.setWord("AA8", "Chinese_Simplified", "光碟");
wlist.setWord("AA8", "Chinese_Traditional", "光碟");
wlist.setWord("AA8", "Chinese_Pinyin", " guāngdié");
wlist.setWord("AA9", "English", "mouse");
wlist.setWord("AA9", "Chinese_Simplified", "滑鼠");
wlist.setWord("AA9", "Chinese_Traditional", "滑鼠");
wlist.setWord("AA9", "Chinese_Pinyin", " huáshǔ");
wlist.setWord("AA10", "English", "laser printer");
wlist.setWord("AA10", "Chinese_Simplified", "激光打印机");
wlist.setWord("AA10", "Chinese_Traditional", "激光打印機");
wlist.setWord("AA10", "Chinese_Pinyin", " jīguāng dǎyìnjī");
wlist.setWord("AA11", "English", "memory");
wlist.setWord("AA11", "Chinese_Simplified", "记忆体");
wlist.setWord("AA11", "Chinese_Traditional", "記憶體");
wlist.setWord("AA11", "Chinese_Pinyin", " jìyì tǐ");
wlist.setWord("AA12", "English", "home computer");
wlist.setWord("AA12", "Chinese_Simplified", "家用电脑");
wlist.setWord("AA12", "Chinese_Traditional", "家用電腦");
wlist.setWord("AA12", "Chinese_Pinyin", " jiāyòng diànnǎo");
wlist.setWord("AA13", "English", "keyboard");
wlist.setWord("AA13", "Chinese_Simplified", "键盘");
wlist.setWord("AA13", "Chinese_Traditional", "鍵盤");
wlist.setWord("AA13", "Chinese_Pinyin", " jiànpán");
wlist.setWord("AA14", "English", "decompression");
wlist.setWord("AA14", "Chinese_Simplified", "解压缩");
wlist.setWord("AA14", "Chinese_Traditional", "解壓縮");
wlist.setWord("AA14", "Chinese_Pinyin", " jiě yāsuō");
wlist.setWord("AA15", "English", "directory/folder");
wlist.setWord("AA15", "Chinese_Simplified", "目录");
wlist.setWord("AA15", "Chinese_Traditional", "目錄");
wlist.setWord("AA15", "Chinese_Pinyin", " mùlù");
wlist.setWord("AA16", "English", "software");
wlist.setWord("AA16", "Chinese_Simplified", "软件");
wlist.setWord("AA16", "Chinese_Traditional", "軟件");
wlist.setWord("AA16", "Chinese_Pinyin", " ruǎnjiàn");
wlist.setWord("AA17", "English", "Windows");
wlist.setWord("AA17", "Chinese_Simplified", "视窗");
wlist.setWord("AA17", "Chinese_Traditional", "視窗");
wlist.setWord("AA17", "Chinese_Pinyin", " shìchuāng");
wlist.setWord("AA18", "English", "icon");
wlist.setWord("AA18", "Chinese_Simplified", "图标");
wlist.setWord("AA18", "Chinese_Traditional", "圖標");
wlist.setWord("AA18", "Chinese_Pinyin", " túbiāo");
wlist.setWord("AA19", "English", "file");
wlist.setWord("AA19", "Chinese_Simplified", "文档");
wlist.setWord("AA19", "Chinese_Traditional", "文檔");
wlist.setWord("AA19", "Chinese_Pinyin", " wéndàng");
wlist.setWord("AA20", "English", "laptop");
wlist.setWord("AA20", "Chinese_Simplified", "膝上型电脑");
wlist.setWord("AA20", "Chinese_Traditional", "膝上型電腦");
wlist.setWord("AA20", "Chinese_Pinyin", " xīshàngxíng diànnǎo");
wlist.setWord("AA21", "English", "monitor");
wlist.setWord("AA21", "Chinese_Simplified", "显示器");
wlist.setWord("AA21", "Chinese_Traditional", "顯示器");
wlist.setWord("AA21", "Chinese_Pinyin", " xiǎnshì qì");
wlist.setWord("AA22", "English", "hardware");
wlist.setWord("AA22", "Chinese_Simplified", "硬体");
wlist.setWord("AA22", "Chinese_Traditional", "硬體");
wlist.setWord("AA22", "Chinese_Pinyin", " yìngtǐ");
wlist.setWord("AA23", "English", "application");
wlist.setWord("AA23", "Chinese_Simplified", "应用程式");
wlist.setWord("AA23", "Chinese_Traditional", "應用程式");
wlist.setWord("AA23", "Chinese_Pinyin", " yìngyòng chéngshì");
wlist.setWord("AA24", "English", "account");
wlist.setWord("AA24", "Chinese_Simplified", "帐户");
wlist.setWord("AA24", "Chinese_Traditional", "帳戶");
wlist.setWord("AA24", "Chinese_Pinyin", " zhànghù");
wlist.setWord("AA25", "English", "motherboard");
wlist.setWord("AA25", "Chinese_Simplified", "主机板");
wlist.setWord("AA25", "Chinese_Traditional", "主機板");
wlist.setWord("AA25", "Chinese_Pinyin", " zhǔjī bǎn");
wlist.setWord("AA26", "English", "desktop computer");
wlist.setWord("AA26", "Chinese_Simplified", "桌上型电脑");
wlist.setWord("AA26", "Chinese_Traditional", "桌上型電腦");
wlist.setWord("AA26", "Chinese_Pinyin", " zhuōshàngxíng diànnǎo");
wlist.setWord("AA27", "English", "processor");
wlist.setWord("AA27", "Chinese_Simplified", "处理器");
wlist.setWord("AA27", "Chinese_Traditional", "處理器");
wlist.setWord("AA27", "Chinese_Pinyin", " chǔlǐ qì");
wlist.setWord("AA28", "English", "to download");
wlist.setWord("AA28", "Chinese_Simplified", "下载");
wlist.setWord("AA28", "Chinese_Traditional", "下載");
wlist.setWord("AA28", "Chinese_Pinyin", " xiàzài");
wlist.setWord("AA29", "English", "LAN");
wlist.setWord("AA29", "Chinese_Simplified", "本地网");
wlist.setWord("AA29", "Chinese_Traditional", "本地網");
wlist.setWord("AA29", "Chinese_Pinyin", " běndiwǎng");
wlist.setWord("AA30", "English", "wireless");
wlist.setWord("AA30", "Chinese_Simplified", "无线");
wlist.setWord("AA30", "Chinese_Traditional", "無綫");
wlist.setWord("AA30", "Chinese_Pinyin", " wúxiàn");
wlist.setWord("AA31", "English", "user");
wlist.setWord("AA31", "Chinese_Simplified", "用户");
wlist.setWord("AA31", "Chinese_Traditional", "用戶");
wlist.setWord("AA31", "Chinese_Pinyin", "yònghù");
wlist.setWord("AA32", "English", "login");
wlist.setWord("AA32", "Chinese_Simplified", "注册");
wlist.setWord("AA32", "Chinese_Traditional", "註冊");
wlist.setWord("AA32", "Chinese_Pinyin", "zhùcè");
wlist.setWord("AA33", "English", "website");
wlist.setWord("AA33", "Chinese_Simplified", "网站");
wlist.setWord("AA33", "Chinese_Traditional", "網站");
wlist.setWord("AA33", "Chinese_Pinyin", "wǎngzhàn");
wlist.setWord("AA34", "English", "internet cafe");
wlist.setWord("AA34", "Chinese_Simplified", "网吧");
wlist.setWord("AA34", "Chinese_Traditional", "網吧");
wlist.setWord("AA34", "Chinese_Pinyin", " wǎngba");
wlist.setWord("AA35", "English", "to browse");
wlist.setWord("AA35", "Chinese_Simplified", "浏览");
wlist.setWord("AA35", "Chinese_Traditional", "瀏覽");
wlist.setWord("AA35", "Chinese_Pinyin", " liúlǎn");
wlist.setWord("AA36", "English", "chat");
wlist.setWord("AA36", "Chinese_Simplified", "聊天");
wlist.setWord("AA36", "Chinese_Traditional", "聊天");
wlist.setWord("AA36", "Chinese_Pinyin", "liáotiān");
