langs = ["Chinese","English","Pinyin"];

wlist = new WordList();

deflang1 = 'English';
deflang2 = 'Chinese';
wlist.setWord("AA2", "English", "Hello");
wlist.setWord("AA2", "Chinese", "你好");
wlist.setWord("AA2", "Pinyin", "Nǐ hǎo");
wlist.setWord("AA3", "English", "How are you?");
wlist.setWord("AA3", "Chinese", "你怎么样");
wlist.setWord("AA3", "Pinyin", "Nǐ zěnme yàng");
wlist.setWord("AA4", "English", "Nice to meet");
wlist.setWord("AA4", "Chinese", "幸会");
wlist.setWord("AA4", "Pinyin", "Xì huì");
wlist.setWord("AA5", "English", "Good morning");
wlist.setWord("AA5", "Chinese", "早上好");
wlist.setWord("AA5", "Pinyin", "Zǎoshàng hǎo");
wlist.setWord("AA6", "English", "Good afternoon");
wlist.setWord("AA6", "Chinese", "下午好");
wlist.setWord("AA6", "Pinyin", "Xiàwǔ");
wlist.setWord("AA7", "English", "Good night");
wlist.setWord("AA7", "Chinese", "晚上好");
wlist.setWord("AA7", "Pinyin", "Wǎnshàng hǎo");
wlist.setWord("AA8", "English", "Goodbye");
wlist.setWord("AA8", "Chinese", "再见");
wlist.setWord("AA8", "Pinyin", "Zàijiàn");
wlist.setWord("AA9", "English", "See you tomorrow");
wlist.setWord("AA9", "Chinese", "明天见");
wlist.setWord("AA9", "Pinyin", "Míngtiān jiàn");
wlist.setWord("AA10", "English", "see you later");
wlist.setWord("AA10", "Chinese", "回头见");
wlist.setWord("AA10", "Pinyin", "Huítóujiàn");
wlist.setWord("AA11", "English", "We'll meet again");
wlist.setWord("AA11", "Chinese", "再会");
wlist.setWord("AA11", "Pinyin", "Zàihuì");
wlist.setWord("AA12", "English", "I have to go");
wlist.setWord("AA12", "Chinese", "我必须走了");
wlist.setWord("AA12", "Pinyin", "wǒbìxūzǒule");
wlist.setWord("AA13", "English", "Where are you going");
wlist.setWord("AA13", "Chinese", "你去哪儿");
wlist.setWord("AA13", "Pinyin", "nǐ qù nǎr");
wlist.setWord("AA14", "English", "I'm going home");
wlist.setWord("AA14", "Chinese", "我回家");
wlist.setWord("AA14", "Pinyin", "Wǒ huí jiā");
wlist.setWord("AA15", "English", "What's your name");
wlist.setWord("AA15", "Chinese", "你叫什么名字");
wlist.setWord("AA15", "Pinyin", "Nǐ jiào shénme míngzi");
wlist.setWord("AA16", "English", "My name is");
wlist.setWord("AA16", "Chinese", "我叫");
wlist.setWord("AA16", "Pinyin", "Wǒ jiào");
wlist.setWord("AA17", "English", "Thank you");
wlist.setWord("AA17", "Chinese", "谢谢");
wlist.setWord("AA17", "Pinyin", "xièxiè");
wlist.setWord("AA18", "English", "What's your surname");
wlist.setWord("AA18", "Chinese", "您贵姓");
wlist.setWord("AA18", "Pinyin", "nín guì xìng");
wlist.setWord("AA19", "English", "Where do you live");
wlist.setWord("AA19", "Chinese", "你住哪儿");
wlist.setWord("AA19", "Pinyin", "Nǐzhùnǎr");
wlist.setWord("AA20", "English", "I live in");
wlist.setWord("AA20", "Chinese", "我住在");
wlist.setWord("AA20", "Pinyin", "Wǒ zhù zài");
wlist.setWord("AA21", "English", "What's you phone number?");
wlist.setWord("AA21", "Chinese", "你的电话是多少");
wlist.setWord("AA21", "Pinyin", "Nǐde diànhuà shì duōshao");
