langs = ["Greek_letter","name"];

wlist = new WordList();

deflang1 = 'name';
deflang2 = 'Greek_letter';
wlist.setWord("Alpha", "name", "Alpha");
wlist.setWord("Alpha", "Greek_letter", "Α α");
wlist.setWord("Beta", "name", "Beta");
wlist.setWord("Beta", "Greek_letter", "Β β");
wlist.setWord("Gamma", "name", "Gamma");
wlist.setWord("Gamma", "Greek_letter", "Γ γ");
wlist.setWord("Delta", "name", "Delta");
wlist.setWord("Delta", "Greek_letter", "Δ δ");
wlist.setWord("Epsilon", "name", "Epsilon");
wlist.setWord("Epsilon", "Greek_letter", "Ε ε");
wlist.setWord("Zeta", "name", "Zeta");
wlist.setWord("Zeta", "Greek_letter", "Ζ ζ");
wlist.setWord("Eta", "name", "Eta");
wlist.setWord("Eta", "Greek_letter", "Η η");
wlist.setWord("Theta", "name", "Theta");
wlist.setWord("Theta", "Greek_letter", "Θ θ");
wlist.setWord("Iota", "name", "Iota");
wlist.setWord("Iota", "Greek_letter", "Ι ι");
wlist.setWord("Kappa", "name", "Kappa");
wlist.setWord("Kappa", "Greek_letter", "Κ κ");
wlist.setWord("Lambda", "name", "Lambda");
wlist.setWord("Lambda", "Greek_letter", "Λ λ");
wlist.setWord("Mu", "name", "Mu");
wlist.setWord("Mu", "Greek_letter", "Μ μ");
wlist.setWord("Nu", "name", "Nu");
wlist.setWord("Nu", "Greek_letter", "Ν ν");
wlist.setWord("Xi", "name", "Xi");
wlist.setWord("Xi", "Greek_letter", "Ξ ξ");
wlist.setWord("Omicron", "name", "Omicron");
wlist.setWord("Omicron", "Greek_letter", "Ο ο");
wlist.setWord("Pi", "name", "Pi");
wlist.setWord("Pi", "Greek_letter", "Π π");
wlist.setWord("Rho", "name", "Rho");
wlist.setWord("Rho", "Greek_letter", "Ρ ρ");
wlist.setWord("Sigma", "name", "Sigma");
wlist.setWord("Sigma", "Greek_letter", "Σ σ");
wlist.setWord("Tau", "name", "Tau");
wlist.setWord("Tau", "Greek_letter", "Τ τ");
wlist.setWord("Upsilon", "name", "Upsilon");
wlist.setWord("Upsilon", "Greek_letter", "Υ υ");
wlist.setWord("Phi", "name", "Phi");
wlist.setWord("Phi", "Greek_letter", "Φ φ");
wlist.setWord("Chi", "name", "Chi");
wlist.setWord("Chi", "Greek_letter", "Χ χ");
wlist.setWord("Psi", "name", "Psi");
wlist.setWord("Psi", "Greek_letter", "Ψ ψ");
wlist.setWord("Omega", "name", "Omega");
wlist.setWord("Omega", "Greek_letter", "Ω ω");
