langs = ["English","Latin"];

wlist = new WordList();

deflang1 = 'English';
deflang2 = 'Latin';
wlist.setWord("AA2", "English", "The play has been performed; applaud!");
wlist.setWord("AA2", "Latin", "acta est fabula plaudite");
wlist.setWord("AA3", "English", "don't speak against the sun");
wlist.setWord("AA3", "Latin", "adversus solem ne loquitor");
wlist.setWord("AA4", "English", "the disease worsens with the treatmen");
wlist.setWord("AA4", "Latin", "aegrescit medendo");
wlist.setWord("AA5", "English", "farewell forever");
wlist.setWord("AA5", "Latin", "aeternum vale");
wlist.setWord("AA6", "English", "the die is cast");
wlist.setWord("AA6", "Latin", "alea iacta est");
wlist.setWord("AA7", "English", "still waters run deep");
wlist.setWord("AA7", "Latin", "altissima quaeque flumina minimo sono labi");
wlist.setWord("AA8", "English", "even a god finds it hard to love and be wise at the same time");
wlist.setWord("AA8", "Latin", "amare et sapere vix deo conceditur");
wlist.setWord("AA9", "English", "a friend of the human race");
wlist.setWord("AA9", "Latin", "amicus humani generis");
wlist.setWord("AA10", "English", "love conquers all");
wlist.setWord("AA10", "Latin", "amor vincit omnia");
wlist.setWord("AA11", "English", "art is long but life is short.");
wlist.setWord("AA11", "Latin", "ars longa vita brevis");
wlist.setWord("AA12", "English", "fortune favours the bold");
wlist.setWord("AA12", "Latin", "audaces fortuna iuvat");
wlist.setWord("AA13", "English", "either learn or leave");
wlist.setWord("AA13", "Latin", "aut disce aut discede");
wlist.setWord("AA14", "English", "I'll either find a way or make one");
wlist.setWord("AA14", "Latin", "aut viam inveniam aut faciam");
wlist.setWord("AA15", "English", "either to conquer or to die");
wlist.setWord("AA15", "Latin", "aut vincere aut mori");
wlist.setWord("AA16", "English", "hail Caesar we who are about to die salute you");
wlist.setWord("AA16", "Latin", "ave Caesar morituri te salutamus");
wlist.setWord("AA17", "English", "to accept a favour is to sell one's freedom");
wlist.setWord("AA17", "Latin", "beneficium accipere libertatem est vendere");
wlist.setWord("AA18", "English", "good wine gladdens a person's heart");
wlist.setWord("AA18", "Latin", "bonum vinum laetificat cor hominis");
wlist.setWord("AA19", "English", "seize the day");
wlist.setWord("AA19", "Latin", "carpe diem");
wlist.setWord("AA20", "English", "let the buyer beware");
wlist.setWord("AA20", "Latin", "caveat emptor");
wlist.setWord("AA21", "English", "I think therefore I exist");
wlist.setWord("AA21", "Latin", "cogito ergo sum");
wlist.setWord("AA22", "English", "with a grain of salt");
wlist.setWord("AA22", "Latin", "cum grano salis");
wlist.setWord("AA23", "English", "of two evils the lesser is always to be chosen");
wlist.setWord("AA23", "Latin", "de duobus malis minus est semper eligendum");
wlist.setWord("AA24", "English", "I have lost a day");
wlist.setWord("AA24", "Latin", "diem perdidi");
wlist.setWord("AA25", "English", "I have spoken");
wlist.setWord("AA25", "Latin", "dixi");
wlist.setWord("AA26", "English", "teach in order to learn");
wlist.setWord("AA26", "Latin", "docendo discimus");
wlist.setWord("AA27", "English", "the law is hard but it is the law");
wlist.setWord("AA27", "Latin", "dura lex sed lex");
wlist.setWord("AA28", "English", "to err is human");
wlist.setWord("AA28", "Latin", "errare humanum est");
wlist.setWord("AA29", "English", "deeds not words");
wlist.setWord("AA29", "Latin", "facta non verba");
wlist.setWord("AA30", "English", "fortune favours the brave");
wlist.setWord("AA30", "Latin", "fortes fortuna iuvat");
wlist.setWord("AA31", "English", "a sound mind in a sound body");
wlist.setWord("AA31", "Latin", "mens sana in corpore sano");
wlist.setWord("AA32", "English", "to sail is necessary; to live is not necessary");
wlist.setWord("AA32", "Latin", "navigare necesse est vivere non est necesse");
wlist.setWord("AA33", "English", "no one is free who is a slave to his body");
wlist.setWord("AA33", "Latin", "nemo liber est qui corpori servit");
wlist.setWord("AA34", "English", "Nobody dances sober");
wlist.setWord("AA34", "Latin", "nemo saltat sobrius");
wlist.setWord("AA35", "English", "Do not disturb my circles!");
wlist.setWord("AA35", "Latin", "noli turbare circulos meos");
wlist.setWord("AA36", "English", "not for you not for me but for us");
wlist.setWord("AA36", "Latin", "non mihi non tibi sed nobis");
wlist.setWord("AA37", "English", "it will not always be summer");
wlist.setWord("AA37", "Latin", "non semper erit aestas");
wlist.setWord("AA38", "English", "second to none");
wlist.setWord("AA38", "Latin", "nulli secundus");
wlist.setWord("AA39", "English", "all things change and we change with them");
wlist.setWord("AA39", "Latin", "omnia mutantur nos et mutamur in illis");
wlist.setWord("AA40", "English", "small things occupy light minds");
wlist.setWord("AA40", "Latin", "parva leves capiunt animas");
wlist.setWord("AA41", "English", "flatterers are the worst type of enemies");
wlist.setWord("AA41", "Latin", "pessimum genus inimicorum laudantes");
wlist.setWord("AA42", "English", "rather to die than to be dishonoured");
wlist.setWord("AA42", "Latin", "potius mori quam foedari");
wlist.setWord("AA43", "English", "whom the gods love die young");
wlist.setWord("AA43", "Latin", "quem di diligunt adolescens moritur");
wlist.setWord("AA44", "English", "what's new?");
wlist.setWord("AA44", "Latin", "quid novi?");
wlist.setWord("AA45", "English", "he who writes reads twice");
wlist.setWord("AA45", "Latin", "qui scribit bis legit");
wlist.setWord("AA46", "English", "repetition is the mother of study");
wlist.setWord("AA46", "Latin", "repetitio est mater studiorum");
wlist.setWord("AA47", "English", "if you did it deny it");
wlist.setWord("AA47", "Latin", "si fecisti nega!");
wlist.setWord("AA48", "English", "Go in peace");
wlist.setWord("AA48", "Latin", "vade in pace");
wlist.setWord("AA49", "English", "I came I saw I conquered");
wlist.setWord("AA49", "Latin", "veni vidi vici");
wlist.setWord("AA50", "English", "the truth shall make you free");
wlist.setWord("AA50", "Latin", "veritas vos liberabit");
wlist.setWord("AA51", "English", "honour to the vanquished");
wlist.setWord("AA51", "Latin", "victis honor");
