langs = ["Chinese","English","Pinyin"];

wlist = new WordList();

deflang1 = 'English';
deflang2 = 'Chinese';
wlist.setWord("AA2", "English", "you");
wlist.setWord("AA2", "Chinese", "你");
wlist.setWord("AA2", "Pinyin", "nǐ");
wlist.setWord("AA3", "English", "good");
wlist.setWord("AA3", "Chinese", "好");
wlist.setWord("AA3", "Pinyin", "hǎo");
wlist.setWord("AA4", "English", "question particle");
wlist.setWord("AA4", "Chinese", "吗");
wlist.setWord("AA4", "Pinyin", "ma");
wlist.setWord("AA5", "English", "I/me");
wlist.setWord("AA5", "Chinese", "我");
wlist.setWord("AA5", "Pinyin", "wǒ");
wlist.setWord("AA6", "English", "very");
wlist.setWord("AA6", "Chinese", "很");
wlist.setWord("AA6", "Pinyin", "hěn");
wlist.setWord("AA7", "English", "question particle");
wlist.setWord("AA7", "Chinese", "呢");
wlist.setWord("AA7", "Pinyin", "ne");
wlist.setWord("AA8", "English", "also/too");
wlist.setWord("AA8", "Chinese", "也");
wlist.setWord("AA8", "Pinyin", "yě");
wlist.setWord("AA9", "English", "busy");
wlist.setWord("AA9", "Chinese", "忙");
wlist.setWord("AA9", "Pinyin", "máng");
wlist.setWord("AA10", "English", "not");
wlist.setWord("AA10", "Chinese", "不");
wlist.setWord("AA10", "Pinyin", "bù");
wlist.setWord("AA11", "English", "elder brother");
wlist.setWord("AA11", "Chinese", "哥哥");
wlist.setWord("AA11", "Pinyin", "gē ge");
wlist.setWord("AA12", "English", "he/him");
wlist.setWord("AA12", "Chinese", "他");
wlist.setWord("AA12", "Pinyin", "tā");
wlist.setWord("AA13", "English", "younger brother");
wlist.setWord("AA13", "Chinese", "弟弟");
wlist.setWord("AA13", "Pinyin", "dì di");
wlist.setWord("AA14", "English", "they");
wlist.setWord("AA14", "Chinese", "他们");
wlist.setWord("AA14", "Pinyin", "tā men");
wlist.setWord("AA15", "English", "all");
wlist.setWord("AA15", "Chinese", "都");
wlist.setWord("AA15", "Pinyin", "dōu");
wlist.setWord("AA16", "English", "this");
wlist.setWord("AA16", "Chinese", "这");
wlist.setWord("AA16", "Pinyin", "zhè");
wlist.setWord("AA17", "English", "to be");
wlist.setWord("AA17", "Chinese", "是");
wlist.setWord("AA17", "Pinyin", "shì");
wlist.setWord("AA18", "English", "friend");
wlist.setWord("AA18", "Chinese", "朋友");
wlist.setWord("AA18", "Pinyin", "péng you");
wlist.setWord("AA19", "English", "father");
wlist.setWord("AA19", "Chinese", "爸爸");
wlist.setWord("AA19", "Pinyin", "bà ba");
wlist.setWord("AA20", "English", "mother");
wlist.setWord("AA20", "Chinese", "妈妈");
wlist.setWord("AA20", "Pinyin", "mā ma");
wlist.setWord("AA21", "English", "you plural");
wlist.setWord("AA21", "Chinese", "你们");
wlist.setWord("AA21", "Pinyin", "nǐ men");
wlist.setWord("AA22", "English", "doctor");
wlist.setWord("AA22", "Chinese", "大夫");
wlist.setWord("AA22", "Pinyin", "dài fu");
wlist.setWord("AA23", "English", "of");
wlist.setWord("AA23", "Chinese", "的");
wlist.setWord("AA23", "Pinyin", "de");
wlist.setWord("AA24", "English", "vehicle");
wlist.setWord("AA24", "Chinese", "车");
wlist.setWord("AA24", "Pinyin", "chē");
wlist.setWord("AA25", "English", "that");
wlist.setWord("AA25", "Chinese", "那");
wlist.setWord("AA25", "Pinyin", "nà");
wlist.setWord("AA26", "English", "she");
wlist.setWord("AA26", "Chinese", "她");
wlist.setWord("AA26", "Pinyin", "tā");
wlist.setWord("AA27", "English", "book");
wlist.setWord("AA27", "Chinese", "书");
wlist.setWord("AA27", "Pinyin", "shū");
wlist.setWord("AA28", "English", "newspaper");
wlist.setWord("AA28", "Chinese", "报");
wlist.setWord("AA28", "Pinyin", "bào");
wlist.setWord("AA29", "English", "paper");
wlist.setWord("AA29", "Chinese", "纸");
wlist.setWord("AA29", "Pinyin", "zhǐ");
wlist.setWord("AA30", "English", "ruler");
wlist.setWord("AA30", "Chinese", "尺");
wlist.setWord("AA30", "Pinyin", "chǐ");
wlist.setWord("AA31", "English", "pen");
wlist.setWord("AA31", "Chinese", "笔");
wlist.setWord("AA31", "Pinyin", "bǐ");
wlist.setWord("AA32", "English", "which");
wlist.setWord("AA32", "Chinese", "哪");
wlist.setWord("AA32", "Pinyin", "nǎ");
wlist.setWord("AA33", "English", "country");
wlist.setWord("AA33", "Chinese", "国");
wlist.setWord("AA33", "Pinyin", "guó");
wlist.setWord("AA34", "English", "person");
wlist.setWord("AA34", "Chinese", "人");
wlist.setWord("AA34", "Pinyin", "rén");
wlist.setWord("AA35", "English", "who");
wlist.setWord("AA35", "Chinese", "谁");
wlist.setWord("AA35", "Pinyin", "shéi");
wlist.setWord("AA36", "English", "we");
wlist.setWord("AA36", "Chinese", "我们");
wlist.setWord("AA36", "Pinyin", "wǒ men");
wlist.setWord("AA37", "English", "teacher");
wlist.setWord("AA37", "Chinese", "老师");
wlist.setWord("AA37", "Pinyin", "lǎo shī");
wlist.setWord("AA38", "English", "spoken Chinese");
wlist.setWord("AA38", "Chinese", "汉语");
wlist.setWord("AA38", "Pinyin", "Hàn yǔ");
wlist.setWord("AA39", "English", "China");
wlist.setWord("AA39", "Chinese", "中国");
wlist.setWord("AA39", "Pinyin", "Zhōng guó");
wlist.setWord("AA40", "English", "Germany");
wlist.setWord("AA40", "Chinese", "德国");
wlist.setWord("AA40", "Pinyin", "Dé guó");
wlist.setWord("AA41", "English", "France");
wlist.setWord("AA41", "Chinese", "法国");
wlist.setWord("AA41", "Pinyin", "Fǎ guó");
wlist.setWord("AA42", "English", "USA");
wlist.setWord("AA42", "Chinese", "美国");
wlist.setWord("AA42", "Pinyin", "Měi guó");
wlist.setWord("AA43", "English", "Mali");
wlist.setWord("AA43", "Chinese", "马里");
wlist.setWord("AA43", "Pinyin", "Mǎ lǐ");
wlist.setWord("AA44", "English", "Japan");
wlist.setWord("AA44", "Chinese", "日本");
wlist.setWord("AA44", "Pinyin", "Rì běn");
wlist.setWord("AA45", "English", "what");
wlist.setWord("AA45", "Chinese", "什么");
wlist.setWord("AA45", "Pinyin", "shén me");
wlist.setWord("AA46", "English", "map");
wlist.setWord("AA46", "Chinese", "地图");
wlist.setWord("AA46", "Pinyin", "dì tú");
wlist.setWord("AA47", "English", "to look");
wlist.setWord("AA47", "Chinese", "看");
wlist.setWord("AA47", "Pinyin", "kàn");
wlist.setWord("AA48", "English", "please");
wlist.setWord("AA48", "Chinese", "请");
wlist.setWord("AA48", "Pinyin", "qǐng");
wlist.setWord("AA49", "English", "Beijing");
wlist.setWord("AA49", "Chinese", "北京");
wlist.setWord("AA49", "Pinyin", "Běi jīng");
wlist.setWord("AA50", "English", "Shanghai");
wlist.setWord("AA50", "Chinese", "上海");
wlist.setWord("AA50", "Pinyin", "Shàng hǎi");
wlist.setWord("AA51", "English", "Yangtse River");
wlist.setWord("AA51", "Chinese", "长江");
wlist.setWord("AA51", "Pinyin", "Cháng Jiāng");
wlist.setWord("AA52", "English", "Yellow River");
wlist.setWord("AA52", "Chinese", "黄河");
wlist.setWord("AA52", "Pinyin", "Huáng Hé");
wlist.setWord("AA53", "English", "the Great Wall");
wlist.setWord("AA53", "Chinese", "长城");
wlist.setWord("AA53", "Pinyin", "Cháng chéng");
wlist.setWord("AA54", "English", "world");
wlist.setWord("AA54", "Chinese", "世界");
wlist.setWord("AA54", "Pinyin", "shì jiè");
wlist.setWord("AA55", "English", "Europe");
wlist.setWord("AA55", "Chinese", "欧洲");
wlist.setWord("AA55", "Pinyin", "ōu zhōu");
wlist.setWord("AA56", "English", "Africa");
wlist.setWord("AA56", "Chinese", "非洲");
wlist.setWord("AA56", "Pinyin", "Fēi Zhōu");
wlist.setWord("AA57", "English", "Oceania");
wlist.setWord("AA57", "Chinese", "大洋周");
wlist.setWord("AA57", "Pinyin", "Dà yáng Zhōu");
wlist.setWord("AA58", "English", "South America");
wlist.setWord("AA58", "Chinese", "南美洲");
wlist.setWord("AA58", "Pinyin", "Nán Měi Zhōu");
wlist.setWord("AA59", "English", "please");
wlist.setWord("AA59", "Chinese", "请");
wlist.setWord("AA59", "Pinyin", "qǐng");
wlist.setWord("AA60", "English", "to drink");
wlist.setWord("AA60", "Chinese", "喝");
wlist.setWord("AA60", "Pinyin", "hē");
wlist.setWord("AA61", "English", "tea");
wlist.setWord("AA61", "Chinese", "茶");
wlist.setWord("AA61", "Pinyin", "chá");
wlist.setWord("AA62", "English", "you");
wlist.setWord("AA62", "Chinese", "您");
wlist.setWord("AA62", "Pinyin", "nín");
wlist.setWord("AA63", "English", "to enter");
wlist.setWord("AA63", "Chinese", "进");
wlist.setWord("AA63", "Pinyin", "jìn");
wlist.setWord("AA64", "English", "to welcome");
wlist.setWord("AA64", "Chinese", "欢迎");
wlist.setWord("AA64", "Pinyin", "huān yíng");
wlist.setWord("AA65", "English", "to thank");
wlist.setWord("AA65", "Chinese", "谢谢");
wlist.setWord("AA65", "Pinyin", "xiè xie");
wlist.setWord("AA66", "English", "polite");
wlist.setWord("AA66", "Chinese", "客气");
wlist.setWord("AA66", "Pinyin", "kè qi");
wlist.setWord("AA67", "English", "to smoke");
wlist.setWord("AA67", "Chinese", "吸烟");
wlist.setWord("AA67", "Pinyin", "xī yān");
wlist.setWord("AA68", "English", "coffee");
wlist.setWord("AA68", "Chinese", "咖啡");
wlist.setWord("AA68", "Pinyin", "kā fēi");
wlist.setWord("AA69", "English", "beer");
wlist.setWord("AA69", "Chinese", "啤酒");
wlist.setWord("AA69", "Pinyin", "pí jiǔ");
wlist.setWord("AA70", "English", "milk");
wlist.setWord("AA70", "Chinese", "牛奶");
wlist.setWord("AA70", "Pinyin", "niú nǎi");
wlist.setWord("AA71", "English", "Mr.");
wlist.setWord("AA71", "Chinese", "先生");
wlist.setWord("AA71", "Pinyin", "xiān sheng");
wlist.setWord("AA72", "English", "Mrs.");
wlist.setWord("AA72", "Chinese", "太太");
wlist.setWord("AA72", "Pinyin", "tài tai");
wlist.setWord("AA73", "English", "what's your name?");
wlist.setWord("AA73", "Chinese", "贵姓");
wlist.setWord("AA73", "Pinyin", "guì xìng");
wlist.setWord("AA74", "English", "May I ask...");
wlist.setWord("AA74", "Chinese", "请问");
wlist.setWord("AA74", "Pinyin", "qǐng wèn");
wlist.setWord("AA75", "English", "to ask");
wlist.setWord("AA75", "Chinese", "问");
wlist.setWord("AA75", "Pinyin", "wèn");
wlist.setWord("AA76", "English", "abroad student");
wlist.setWord("AA76", "Chinese", "留学生");
wlist.setWord("AA76", "Pinyin", "liú xué shēng");
wlist.setWord("AA77", "English", "surname");
wlist.setWord("AA77", "Chinese", "姓");
wlist.setWord("AA77", "Pinyin", "xìng");
wlist.setWord("AA78", "English", "to call");
wlist.setWord("AA78", "Chinese", "叫");
wlist.setWord("AA78", "Pinyin", "jiào");
wlist.setWord("AA79", "English", "foreign language");
wlist.setWord("AA79", "Chinese", "外语");
wlist.setWord("AA79", "Pinyin", "wài yǔ");
wlist.setWord("AA80", "English", "college");
wlist.setWord("AA80", "Chinese", "学院");
wlist.setWord("AA80", "Pinyin", "xué yuàn");
wlist.setWord("AA81", "English", "student");
wlist.setWord("AA81", "Chinese", "学生");
wlist.setWord("AA81", "Pinyin", "xué sheng");
wlist.setWord("AA82", "English", "to study/to learn");
wlist.setWord("AA82", "Chinese", "学习");
wlist.setWord("AA82", "Pinyin", "xué xí");
wlist.setWord("AA83", "English", "miss");
wlist.setWord("AA83", "Chinese", "小姐");
wlist.setWord("AA83", "Pinyin", "xiǎo jie");
wlist.setWord("AA84", "English", "madam");
wlist.setWord("AA84", "Chinese", "女士");
wlist.setWord("AA84", "Pinyin", "nǚ shì");
wlist.setWord("AA85", "English", "comrade");
wlist.setWord("AA85", "Chinese", "同志");
wlist.setWord("AA85", "Pinyin", "tóng zhì");
wlist.setWord("AA86", "English", "Korea");
wlist.setWord("AA86", "Chinese", "朝鲜");
wlist.setWord("AA86", "Pinyin", "Cháo xiǎn");
wlist.setWord("AA87", "English", "Britain");
wlist.setWord("AA87", "Chinese", "英国");
wlist.setWord("AA87", "Pinyin", "Yīng guó");
wlist.setWord("AA88", "English", "in");
wlist.setWord("AA88", "Chinese", "在");
wlist.setWord("AA88", "Pinyin", "zài");
wlist.setWord("AA89", "English", "to sit");
wlist.setWord("AA89", "Chinese", "坐");
wlist.setWord("AA89", "Pinyin", "zuò");
wlist.setWord("AA90", "English", "where");
wlist.setWord("AA90", "Chinese", "哪儿");
wlist.setWord("AA90", "Pinyin", "nǎr");
wlist.setWord("AA91", "English", "dormitory");
wlist.setWord("AA91", "Chinese", "宿舍");
wlist.setWord("AA91", "Pinyin", "sù shè");
wlist.setWord("AA92", "English", "to live");
wlist.setWord("AA92", "Chinese", "住");
wlist.setWord("AA92", "Pinyin", "zhù");
wlist.setWord("AA93", "English", "how much");
wlist.setWord("AA93", "Chinese", "多少");
wlist.setWord("AA93", "Pinyin", "duō shao");
wlist.setWord("AA94", "English", "number");
wlist.setWord("AA94", "Chinese", "号");
wlist.setWord("AA94", "Pinyin", "hào");
wlist.setWord("AA95", "English", "story of a building");
wlist.setWord("AA95", "Chinese", "层");
wlist.setWord("AA95", "Pinyin", "céng");
wlist.setWord("AA96", "English", "hospital");
wlist.setWord("AA96", "Chinese", "医院");
wlist.setWord("AA96", "Pinyin", "yī yuàn");
wlist.setWord("AA97", "English", "toilet");
wlist.setWord("AA97", "Chinese", "厕所");
wlist.setWord("AA97", "Pinyin", "cè suǒ");
wlist.setWord("AA98", "English", "here");
wlist.setWord("AA98", "Chinese", "这儿");
wlist.setWord("AA98", "Pinyin", "zhèr");
wlist.setWord("AA99", "English", "there");
wlist.setWord("AA99", "Chinese", "那儿");
wlist.setWord("AA99", "Pinyin", "nàr");
