langs = ["Chinese","English","PinYin"];

wlist = new WordList();

wlist.setWord("AA2", "Chinese", "还");
wlist.setWord("AA2", "PinYin", "huán");
wlist.setWord("AA2", "English", "to return");
wlist.setWord("AA3", "Chinese", "画报");
wlist.setWord("AA3", "PinYin", "huà bào");
wlist.setWord("AA3", "English", "magazine");
wlist.setWord("AA4", "Chinese", "词典");
wlist.setWord("AA4", "PinYin", "cí diǎn");
wlist.setWord("AA4", "English", "dictionary");
wlist.setWord("AA5", "Chinese", "现在");
wlist.setWord("AA5", "PinYin", "xiàn zài");
wlist.setWord("AA5", "English", "now");
wlist.setWord("AA6", "Chinese", "用");
wlist.setWord("AA6", "PinYin", "yòng");
wlist.setWord("AA6", "English", "to use");
wlist.setWord("AA7", "Chinese", "一下儿");
wlist.setWord("AA7", "PinYin", "yí xiàr");
wlist.setWord("AA7", "English", "a little bit");
wlist.setWord("AA8", "Chinese", "再见");
wlist.setWord("AA8", "PinYin", "zài jiàn");
wlist.setWord("AA8", "English", "goodbye");
wlist.setWord("AA9", "Chinese", "杂志");
wlist.setWord("AA9", "PinYin", "zá zhì");
wlist.setWord("AA9", "English", "magazine");
wlist.setWord("AA10", "Chinese", "电话");
wlist.setWord("AA10", "PinYin", "diàn huà");
wlist.setWord("AA10", "English", "telephone");
wlist.setWord("AA11", "Chinese", "本子");
wlist.setWord("AA11", "PinYin", "běn zi");
wlist.setWord("AA11", "English", "notebook");
wlist.setWord("AA12", "Chinese", "雨伞");
wlist.setWord("AA12", "PinYin", "yǔ sǎn");
wlist.setWord("AA12", "English", "umbrella");
wlist.setWord("AA13", "Chinese", "女");
wlist.setWord("AA13", "PinYin", "nǚ");
wlist.setWord("AA13", "English", "female");
wlist.setWord("AA14", "Chinese", "先生");
wlist.setWord("AA14", "PinYin", "xiān sheng");
wlist.setWord("AA14", "English", "Mr.");
wlist.setWord("AA15", "Chinese", "认识");
wlist.setWord("AA15", "PinYin", "rèn shi");
wlist.setWord("AA15", "English", "to know");
wlist.setWord("AA16", "Chinese", "英语");
wlist.setWord("AA16", "PinYin", "Yīng yǔ");
wlist.setWord("AA16", "English", "English");
wlist.setWord("AA17", "Chinese", "法语");
wlist.setWord("AA17", "PinYin", "Fǎ yǔ");
wlist.setWord("AA17", "English", "French");
wlist.setWord("AA18", "Chinese", "常");
wlist.setWord("AA18", "PinYin", "cháng");
wlist.setWord("AA18", "English", "often");
wlist.setWord("AA19", "Chinese", "去");
wlist.setWord("AA19", "PinYin", "qù");
wlist.setWord("AA19", "English", "to go");
wlist.setWord("AA20", "Chinese", "他们");
wlist.setWord("AA20", "PinYin", "tā men");
wlist.setWord("AA20", "English", "they");
wlist.setWord("AA21", "Chinese", "喂");
wlist.setWord("AA21", "PinYin", "wèi");
wlist.setWord("AA21", "English", "hello");
wlist.setWord("AA22", "Chinese", "啊");
wlist.setWord("AA22", "PinYin", "ā");
wlist.setWord("AA22", "English", "oh!");
wlist.setWord("AA23", "Chinese", "商店");
wlist.setWord("AA23", "PinYin", "shāng diàn");
wlist.setWord("AA23", "English", "shop");
wlist.setWord("AA24", "Chinese", "买");
wlist.setWord("AA24", "PinYin", "mǎi");
wlist.setWord("AA24", "English", "to buy");
wlist.setWord("AA25", "Chinese", "笔");
wlist.setWord("AA25", "PinYin", "bǐ");
wlist.setWord("AA25", "English", "pen/pencil");
wlist.setWord("AA26", "Chinese", "纸");
wlist.setWord("AA26", "PinYin", "zhǐ");
wlist.setWord("AA26", "English", "paper");
wlist.setWord("AA27", "Chinese", "来");
wlist.setWord("AA27", "PinYin", "lái");
wlist.setWord("AA27", "English", "to come");
wlist.setWord("AA28", "Chinese", "介绍");
wlist.setWord("AA28", "PinYin", "jiè shào");
wlist.setWord("AA28", "English", "to introduce");
wlist.setWord("AA29", "Chinese", "男");
wlist.setWord("AA29", "PinYin", "nán");
wlist.setWord("AA29", "English", "male");
wlist.setWord("AA30", "Chinese", "对");
wlist.setWord("AA30", "PinYin", "duì");
wlist.setWord("AA30", "English", "correct");
wlist.setWord("AA31", "Chinese", "和");
wlist.setWord("AA31", "PinYin", "hé");
wlist.setWord("AA31", "English", "and");
wlist.setWord("AA32", "Chinese", "说");
wlist.setWord("AA32", "PinYin", "shuō");
wlist.setWord("AA32", "English", "to speak");
wlist.setWord("AA33", "Chinese", "中国");
wlist.setWord("AA33", "PinYin", "Zhōng guó");
wlist.setWord("AA33", "English", "China");
wlist.setWord("AA34", "Chinese", "英国");
wlist.setWord("AA34", "PinYin", "Yīng guó");
wlist.setWord("AA34", "English", "Britain");
wlist.setWord("AA35", "Chinese", "法国");
wlist.setWord("AA35", "PinYin", "Fǎ guó");
wlist.setWord("AA35", "English", "France");
wlist.setWord("AA36", "Chinese", "邮局");
wlist.setWord("AA36", "PinYin", "yóu jú");
wlist.setWord("AA36", "English", "post office");
wlist.setWord("AA37", "Chinese", "邮票");
wlist.setWord("AA37", "PinYin", "yóu piào");
wlist.setWord("AA37", "English", "stamp");
wlist.setWord("AA38", "Chinese", "教授");
wlist.setWord("AA38", "PinYin", "jiào shòu");
wlist.setWord("AA38", "English", "professor");
wlist.setWord("AA39", "Chinese", "作");
wlist.setWord("AA39", "PinYin", "zuò");
wlist.setWord("AA39", "English", "to do");
wlist.setWord("AA40", "Chinese", "工作");
wlist.setWord("AA40", "PinYin", "gōng zuò");
wlist.setWord("AA40", "English", "to work");
wlist.setWord("AA41", "Chinese", "想");
wlist.setWord("AA41", "PinYin", "xiǎng");
wlist.setWord("AA41", "English", "to want");
wlist.setWord("AA42", "Chinese", "家");
wlist.setWord("AA42", "PinYin", "jiā");
wlist.setWord("AA42", "English", "home");
wlist.setWord("AA43", "Chinese", "有");
wlist.setWord("AA43", "PinYin", "yǒu");
wlist.setWord("AA43", "English", "to have");
wlist.setWord("AA44", "Chinese", "没");
wlist.setWord("AA44", "PinYin", "méi");
wlist.setWord("AA44", "English", "have not");
wlist.setWord("AA45", "Chinese", "妹妹");
wlist.setWord("AA45", "PinYin", "mèi mei");
wlist.setWord("AA45", "English", "younger sister");
wlist.setWord("AA46", "Chinese", "姐姐");
wlist.setWord("AA46", "PinYin", "jiě jie");
wlist.setWord("AA46", "English", "older sister");
wlist.setWord("AA47", "Chinese", "银行");
wlist.setWord("AA47", "PinYin", "yín háng");
wlist.setWord("AA47", "English", "bank");
wlist.setWord("AA48", "Chinese", "爱人");
wlist.setWord("AA48", "PinYin", "ài ren");
wlist.setWord("AA48", "English", "husband/wife");
wlist.setWord("AA49", "Chinese", "书店");
wlist.setWord("AA49", "PinYin", "shū diàn");
wlist.setWord("AA49", "English", "bookstore");
wlist.setWord("AA50", "Chinese", "孩子");
wlist.setWord("AA50", "PinYin", "hái zi");
wlist.setWord("AA50", "English", "child");
wlist.setWord("AA51", "Chinese", "给");
wlist.setWord("AA51", "PinYin", "gěi");
wlist.setWord("AA51", "English", "to give");
wlist.setWord("AA52", "Chinese", "写");
wlist.setWord("AA52", "PinYin", "xiě");
wlist.setWord("AA52", "English", "to write");
wlist.setWord("AA53", "Chinese", "信");
wlist.setWord("AA53", "PinYin", "xìn");
wlist.setWord("AA53", "English", "letter");
wlist.setWord("AA54", "Chinese", "告诉");
wlist.setWord("AA54", "PinYin", "gào su");
wlist.setWord("AA54", "English", "to tell");
wlist.setWord("AA55", "Chinese", "职员");
wlist.setWord("AA55", "PinYin", "zhí yuán");
wlist.setWord("AA55", "English", "office worker");
wlist.setWord("AA56", "Chinese", "工程师");
wlist.setWord("AA56", "PinYin", "gōng chéng shī");
wlist.setWord("AA56", "English", "engineer");
wlist.setWord("AA57", "Chinese", "经理");
wlist.setWord("AA57", "PinYin", "jīng lǐ");
wlist.setWord("AA57", "English", "manager");
wlist.setWord("AA58", "Chinese", "公司");
wlist.setWord("AA58", "PinYin", "gōng sī");
wlist.setWord("AA58", "English", "company");
wlist.setWord("AA59", "Chinese", "中文");
wlist.setWord("AA59", "PinYin", "Zhōng wén");
wlist.setWord("AA59", "English", "written Chinese");
wlist.setWord("AA60", "Chinese", "系");
wlist.setWord("AA60", "PinYin", "xì");
wlist.setWord("AA60", "English", "department");
wlist.setWord("AA61", "Chinese", "几");
wlist.setWord("AA61", "PinYin", "jǐ");
wlist.setWord("AA61", "English", "how much");
wlist.setWord("AA62", "Chinese", "教");
wlist.setWord("AA62", "PinYin", "jiāo");
wlist.setWord("AA62", "English", "to teach");
wlist.setWord("AA63", "Chinese", "语法");
wlist.setWord("AA63", "PinYin", "yǔ fǎ");
wlist.setWord("AA63", "English", "grammar");
wlist.setWord("AA64", "Chinese", "汉字");
wlist.setWord("AA64", "PinYin", "Hàn zì");
wlist.setWord("AA64", "English", "Chinese character");
wlist.setWord("AA65", "Chinese", "字");
wlist.setWord("AA65", "PinYin", "zì");
wlist.setWord("AA65", "English", "character");
wlist.setWord("AA66", "Chinese", "还");
wlist.setWord("AA66", "PinYin", "hái");
wlist.setWord("AA66", "English", "else");
wlist.setWord("AA67", "Chinese", "口语");
wlist.setWord("AA67", "PinYin", "kǒu yǔ");
wlist.setWord("AA67", "English", "spoken language");
wlist.setWord("AA68", "Chinese", "不敢当");
wlist.setWord("AA68", "PinYin", "bù gǎn dāng");
wlist.setWord("AA68", "English", "you flatter me");
wlist.setWord("AA69", "Chinese", "互相");
wlist.setWord("AA69", "PinYin", "hù xiāng");
wlist.setWord("AA69", "English", "mutual");
wlist.setWord("AA70", "Chinese", "新");
wlist.setWord("AA70", "PinYin", "xīn");
wlist.setWord("AA70", "English", "new");
wlist.setWord("AA71", "Chinese", "阅览室");
wlist.setWord("AA71", "PinYin", "yuè lǎn shì");
wlist.setWord("AA71", "English", "reading room");
wlist.setWord("AA72", "Chinese", "杂志");
wlist.setWord("AA72", "PinYin", "zá zhì");
wlist.setWord("AA72", "English", "magazine");
wlist.setWord("AA73", "Chinese", "报");
wlist.setWord("AA73", "PinYin", "bào");
wlist.setWord("AA73", "English", "newspaper");
wlist.setWord("AA74", "Chinese", "图书馆");
wlist.setWord("AA74", "PinYin", "tú shū guǎn");
wlist.setWord("AA74", "English", "library");
wlist.setWord("AA75", "Chinese", "那儿");
wlist.setWord("AA75", "PinYin", "nàr");
wlist.setWord("AA75", "English", "there");
wlist.setWord("AA76", "Chinese", "班");
wlist.setWord("AA76", "PinYin", "bān");
wlist.setWord("AA76", "English", "class");
wlist.setWord("AA77", "Chinese", "教室");
wlist.setWord("AA77", "PinYin", "jiào shì");
wlist.setWord("AA77", "English", "classroom");
wlist.setWord("AA78", "Chinese", "实验室");
wlist.setWord("AA78", "PinYin", "shí yàn shì");
wlist.setWord("AA78", "English", "laboratory");
wlist.setWord("AA79", "Chinese", "借");
wlist.setWord("AA79", "PinYin", "jiè");
wlist.setWord("AA79", "English", "to borrow");
wlist.setWord("AA80", "Chinese", "生词");
wlist.setWord("AA80", "PinYin", "shēng cí");
wlist.setWord("AA80", "English", "new word");
wlist.setWord("AA81", "Chinese", "裙子");
wlist.setWord("AA81", "PinYin", "qún zi");
wlist.setWord("AA81", "English", "skirt");
wlist.setWord("AA82", "Chinese", "两");
wlist.setWord("AA82", "PinYin", "liǎng");
wlist.setWord("AA82", "English", "two");
wlist.setWord("AA83", "Chinese", "票");
wlist.setWord("AA83", "PinYin", "piào");
wlist.setWord("AA83", "English", "ticket");
wlist.setWord("AA84", "Chinese", "京剧");
wlist.setWord("AA84", "PinYin", "jīng jù");
wlist.setWord("AA84", "English", "Beijing opera");
wlist.setWord("AA85", "Chinese", "晚上");
wlist.setWord("AA85", "PinYin", "wǎn shang");
wlist.setWord("AA85", "English", "evening");
wlist.setWord("AA86", "Chinese", "太");
wlist.setWord("AA86", "PinYin", "tài");
wlist.setWord("AA86", "English", "too much");
wlist.setWord("AA87", "Chinese", "从");
wlist.setWord("AA87", "PinYin", "cóng");
wlist.setWord("AA87", "English", "from");
wlist.setWord("AA88", "Chinese", "找");
wlist.setWord("AA88", "PinYin", "zhǎo");
wlist.setWord("AA88", "English", "to look for");
wlist.setWord("AA89", "Chinese", "这儿");
wlist.setWord("AA89", "PinYin", "zhèr");
wlist.setWord("AA89", "English", "here");
wlist.setWord("AA90", "Chinese", "旧");
wlist.setWord("AA90", "PinYin", "jiù");
wlist.setWord("AA90", "English", "old");
wlist.setWord("AA91", "Chinese", "穿");
wlist.setWord("AA91", "PinYin", "chuān");
wlist.setWord("AA91", "English", "to put on/to wear");
wlist.setWord("AA92", "Chinese", "衬衫");
wlist.setWord("AA92", "PinYin", "chèn shān");
wlist.setWord("AA92", "English", "shirt");
wlist.setWord("AA93", "Chinese", "绿");
wlist.setWord("AA93", "PinYin", "lǜ");
wlist.setWord("AA93", "English", "green");
wlist.setWord("AA94", "Chinese", "大");
wlist.setWord("AA94", "PinYin", "dà");
wlist.setWord("AA94", "English", "big");
wlist.setWord("AA95", "Chinese", "白");
wlist.setWord("AA95", "PinYin", "bái");
wlist.setWord("AA95", "English", "white");
wlist.setWord("AA96", "Chinese", "蓝");
wlist.setWord("AA96", "PinYin", "lán");
wlist.setWord("AA96", "English", "blue");
wlist.setWord("AA97", "Chinese", "上衣");
wlist.setWord("AA97", "PinYin", "shàng yī");
wlist.setWord("AA97", "English", "jacket");
wlist.setWord("AA98", "Chinese", "裤子");
wlist.setWord("AA98", "PinYin", "kù zi");
wlist.setWord("AA98", "English", "trousers");
wlist.setWord("AA99", "Chinese", "大衣");
wlist.setWord("AA99", "PinYin", "dà yī");
wlist.setWord("AA99", "English", "topcoat");
wlist.setWord("AA100", "Chinese", "黑");
wlist.setWord("AA100", "PinYin", "hēi");
wlist.setWord("AA100", "English", "black");
wlist.setWord("AA101", "Chinese", "剧场");
wlist.setWord("AA101", "PinYin", "jù chǎng");
wlist.setWord("AA101", "English", "theatre");
wlist.setWord("AA102", "Chinese", "座位");
wlist.setWord("AA102", "PinYin", "zuò wèi");
wlist.setWord("AA102", "English", "seat");
wlist.setWord("AA103", "Chinese", "食堂");
wlist.setWord("AA103", "PinYin", "shí táng");
wlist.setWord("AA103", "English", "dining-hall");
wlist.setWord("AA104", "Chinese", "差");
wlist.setWord("AA104", "PinYin", "chà");
wlist.setWord("AA104", "English", "to lack");
wlist.setWord("AA105", "Chinese", "分");
wlist.setWord("AA105", "PinYin", "fēn");
wlist.setWord("AA105", "English", "minute");
wlist.setWord("AA106", "Chinese", "刻");
wlist.setWord("AA106", "PinYin", "kè");
wlist.setWord("AA106", "English", "quarter of an hour");
wlist.setWord("AA107", "Chinese", "上课");
wlist.setWord("AA107", "PinYin", "shàng kè");
wlist.setWord("AA107", "English", "to attend a class");
wlist.setWord("AA108", "Chinese", "课");
wlist.setWord("AA108", "PinYin", "kè");
wlist.setWord("AA108", "English", "class/lesson");
wlist.setWord("AA109", "Chinese", "下课");
wlist.setWord("AA109", "PinYin", "xià kè");
wlist.setWord("AA109", "English", "class is over");
wlist.setWord("AA110", "Chinese", "以后");
wlist.setWord("AA110", "PinYin", "yǐ hòu");
wlist.setWord("AA110", "English", "later on");
wlist.setWord("AA111", "Chinese", "事儿");
wlist.setWord("AA111", "PinYin", "shìr");
wlist.setWord("AA111", "English", "thing");
wlist.setWord("AA112", "Chinese", "回");
wlist.setWord("AA112", "PinYin", "huí");
wlist.setWord("AA112", "English", "to return");
wlist.setWord("AA113", "Chinese", "跟");
wlist.setWord("AA113", "PinYin", "gēn");
wlist.setWord("AA113", "English", "to follow");
wlist.setWord("AA114", "Chinese", "一起");
wlist.setWord("AA114", "PinYin", "yì qǐ");
wlist.setWord("AA114", "English", "together");
wlist.setWord("AA115", "Chinese", "电影");
wlist.setWord("AA115", "PinYin", "diàn yǐng");
wlist.setWord("AA115", "English", "movie");
wlist.setWord("AA116", "Chinese", "咖啡馆");
wlist.setWord("AA116", "PinYin", "kā fēi guǎn");
wlist.setWord("AA116", "English", "cafe");
wlist.setWord("AA117", "Chinese", "咖啡");
wlist.setWord("AA117", "PinYin", "kā fēi");
wlist.setWord("AA117", "English", "coffee");
wlist.setWord("AA118", "Chinese", "半");
wlist.setWord("AA118", "PinYin", "bàn");
wlist.setWord("AA118", "English", "half");
wlist.setWord("AA119", "Chinese", "等");
wlist.setWord("AA119", "PinYin", "děng");
wlist.setWord("AA119", "English", "to wait");
wlist.setWord("AA120", "Chinese", "走");
wlist.setWord("AA120", "PinYin", "zǒu");
wlist.setWord("AA120", "English", "to walk");
wlist.setWord("AA121", "Chinese", "路");
wlist.setWord("AA121", "PinYin", "lù");
wlist.setWord("AA121", "English", "road");
wlist.setWord("AA122", "Chinese", "上班");
wlist.setWord("AA122", "PinYin", "shàng bān");
wlist.setWord("AA122", "English", "to go to work");
wlist.setWord("AA123", "Chinese", "下班");
wlist.setWord("AA123", "PinYin", "xià bān");
wlist.setWord("AA123", "English", "go off work");
wlist.setWord("AA124", "Chinese", "电影院");
wlist.setWord("AA124", "PinYin", "diàn yǐng yuàn");
wlist.setWord("AA124", "English", "cinema");
wlist.setWord("AA125", "Chinese", "表");
wlist.setWord("AA125", "PinYin", "biǎo");
wlist.setWord("AA125", "English", "a watch");
wlist.setWord("AA126", "Chinese", "钟");
wlist.setWord("AA126", "PinYin", "zhōng");
wlist.setWord("AA126", "English", "clock");
wlist.setWord("AA127", "Chinese", "以前");
wlist.setWord("AA127", "PinYin", "yǐ qián");
wlist.setWord("AA127", "English", "before");
wlist.setWord("AA128", "Chinese", "天");
wlist.setWord("AA128", "PinYin", "tiān");
wlist.setWord("AA128", "English", "day");
wlist.setWord("AA129", "Chinese", "每");
wlist.setWord("AA129", "PinYin", "měi");
wlist.setWord("AA129", "English", "every");
wlist.setWord("AA130", "Chinese", "起床");
wlist.setWord("AA130", "PinYin", "qǐ chuáng");
wlist.setWord("AA130", "English", "to get up");
wlist.setWord("AA131", "Chinese", "起");
wlist.setWord("AA131", "PinYin", "qǐ");
wlist.setWord("AA131", "English", "to rise");
wlist.setWord("AA132", "Chinese", "床");
wlist.setWord("AA132", "PinYin", "chuáng");
wlist.setWord("AA132", "English", "bed");
wlist.setWord("AA133", "Chinese", "上午");
wlist.setWord("AA133", "PinYin", "shàng wǔ");
wlist.setWord("AA133", "English", "morning");
wlist.setWord("AA134", "Chinese", "吃");
wlist.setWord("AA134", "PinYin", "chī");
wlist.setWord("AA134", "English", "to eat");
wlist.setWord("AA135", "Chinese", "饭");
wlist.setWord("AA135", "PinYin", "fàn");
wlist.setWord("AA135", "English", "meal");
wlist.setWord("AA136", "Chinese", "多");
wlist.setWord("AA136", "PinYin", "duō");
wlist.setWord("AA136", "English", "many");
wlist.setWord("AA137", "Chinese", "下午");
wlist.setWord("AA137", "PinYin", "xià wǔ");
wlist.setWord("AA137", "English", "afternoon");
wlist.setWord("AA138", "Chinese", "休息");
wlist.setWord("AA138", "PinYin", "xiū xi");
wlist.setWord("AA138", "English", "to rest");
wlist.setWord("AA139", "Chinese", "有时候");
wlist.setWord("AA139", "PinYin", "yǒu shí hou");
wlist.setWord("AA139", "English", "sometimes");
wlist.setWord("AA140", "Chinese", "时候");
wlist.setWord("AA140", "PinYin", "shí hou");
wlist.setWord("AA140", "English", "time");
wlist.setWord("AA141", "Chinese", "问题");
wlist.setWord("AA141", "PinYin", "wèn tí");
wlist.setWord("AA141", "English", "question");
wlist.setWord("AA142", "Chinese", "睡觉");
wlist.setWord("AA142", "PinYin", "shuì jiào");
wlist.setWord("AA142", "English", "to sleep");
wlist.setWord("AA143", "Chinese", "要");
wlist.setWord("AA143", "PinYin", "yào");
wlist.setWord("AA143", "English", "to want");
wlist.setWord("AA144", "Chinese", "服务员");
wlist.setWord("AA144", "PinYin", "fú wù yuán");
wlist.setWord("AA144", "English", "waiter");
wlist.setWord("AA145", "Chinese", "杯");
wlist.setWord("AA145", "PinYin", "bēi");
wlist.setWord("AA145", "English", "cup");
wlist.setWord("AA146", "Chinese", "小姐");
wlist.setWord("AA146", "PinYin", "xiǎo jie");
wlist.setWord("AA146", "English", "miss");
wlist.setWord("AA147", "Chinese", "喜欢");
wlist.setWord("AA147", "PinYin", "xǐ huan");
wlist.setWord("AA147", "English", "to like");
wlist.setWord("AA148", "Chinese", "花茶");
wlist.setWord("AA148", "PinYin", "huā chá");
wlist.setWord("AA148", "English", "scented tea");
wlist.setWord("AA149", "Chinese", "红茶");
wlist.setWord("AA149", "PinYin", "hóng chá");
wlist.setWord("AA149", "English", "black tea");
wlist.setWord("AA150", "Chinese", "红");
wlist.setWord("AA150", "PinYin", "hóng");
wlist.setWord("AA150", "English", "red");
wlist.setWord("AA151", "Chinese", "还是");
wlist.setWord("AA151", "PinYin", "hái shì");
wlist.setWord("AA151", "English", "or");
wlist.setWord("AA152", "Chinese", "桔子水");
wlist.setWord("AA152", "PinYin", "jú zi shuǐ");
wlist.setWord("AA152", "English", "orange juice");
wlist.setWord("AA153", "Chinese", "桔子");
wlist.setWord("AA153", "PinYin", "jú zi");
wlist.setWord("AA153", "English", "orange");
wlist.setWord("AA154", "Chinese", "水");
wlist.setWord("AA154", "PinYin", "shuǐ");
wlist.setWord("AA154", "English", "water");
wlist.setWord("AA155", "Chinese", "瓶");
wlist.setWord("AA155", "PinYin", "píng");
wlist.setWord("AA155", "English", "bottle");
wlist.setWord("AA156", "Chinese", "啤酒");
wlist.setWord("AA156", "PinYin", "pí jiǔ");
wlist.setWord("AA156", "English", "beer");
wlist.setWord("AA157", "Chinese", "听");
wlist.setWord("AA157", "PinYin", "tīng");
wlist.setWord("AA157", "English", "to listen");
wlist.setWord("AA158", "Chinese", "民歌");
wlist.setWord("AA158", "PinYin", "mín gē");
wlist.setWord("AA158", "English", "folk song");
wlist.setWord("AA159", "Chinese", "古典");
wlist.setWord("AA159", "PinYin", "gǔ diǎn");
wlist.setWord("AA159", "English", "classical");
wlist.setWord("AA160", "Chinese", "音乐");
wlist.setWord("AA160", "PinYin", "yīn yuè");
wlist.setWord("AA160", "English", "music");
wlist.setWord("AA161", "Chinese", "现代");
wlist.setWord("AA161", "PinYin", "xiàn dài");
wlist.setWord("AA161", "English", "modern");
wlist.setWord("AA162", "Chinese", "唱");
wlist.setWord("AA162", "PinYin", "chàng");
wlist.setWord("AA162", "English", "to sing");
wlist.setWord("AA163", "Chinese", "歌儿");
wlist.setWord("AA163", "PinYin", "gēr");
wlist.setWord("AA163", "English", "song");
wlist.setWord("AA164", "Chinese", "让");
wlist.setWord("AA164", "PinYin", "ràng");
wlist.setWord("AA164", "English", "to ask");
wlist.setWord("AA165", "Chinese", "别");
wlist.setWord("AA165", "PinYin", "bié");
wlist.setWord("AA165", "English", "do not");
wlist.setWord("AA166", "Chinese", "枝");
wlist.setWord("AA166", "PinYin", "zhī");
wlist.setWord("AA166", "English", "branch");
wlist.setWord("AA167", "Chinese", "苹果");
wlist.setWord("AA167", "PinYin", "píng guǒ");
wlist.setWord("AA167", "English", "apple");
wlist.setWord("AA168", "Chinese", "香蕉");
wlist.setWord("AA168", "PinYin", "xiāng jiāo");
wlist.setWord("AA168", "English", "banana");
wlist.setWord("AA169", "Chinese", "葡萄");
wlist.setWord("AA169", "PinYin", "pú tao");
wlist.setWord("AA169", "English", "grape");
wlist.setWord("AA170", "Chinese", "唱片");
wlist.setWord("AA170", "PinYin", "chàng piàn");
wlist.setWord("AA170", "English", "record");
wlist.setWord("AA171", "Chinese", "绿茶");
wlist.setWord("AA171", "PinYin", "lǜ chá");
wlist.setWord("AA171", "English", "green tea");
wlist.setWord("AA172", "Chinese", "月");
wlist.setWord("AA172", "PinYin", "yuè");
wlist.setWord("AA172", "English", "month");
wlist.setWord("AA173", "Chinese", "生日");
wlist.setWord("AA173", "PinYin", "shēng rì");
wlist.setWord("AA173", "English", "birthday");
wlist.setWord("AA174", "Chinese", "今天");
wlist.setWord("AA174", "PinYin", "jīn tiān");
wlist.setWord("AA174", "English", "today");
wlist.setWord("AA175", "Chinese", "班");
wlist.setWord("AA175", "PinYin", "bān");
wlist.setWord("AA175", "English", "class");
wlist.setWord("AA176", "Chinese", "辅导");
wlist.setWord("AA176", "PinYin", "fǔ dǎo");
wlist.setWord("AA176", "English", "to coach");
wlist.setWord("AA177", "Chinese", "号");
wlist.setWord("AA177", "PinYin", "hào");
wlist.setWord("AA177", "English", "day of a month");
wlist.setWord("AA178", "Chinese", "空儿");
wlist.setWord("AA178", "PinYin", "kòngr");
wlist.setWord("AA178", "English", "free time");
wlist.setWord("AA179", "Chinese", "今年");
wlist.setWord("AA179", "PinYin", "jīn nián");
wlist.setWord("AA179", "English", "this year");
wlist.setWord("AA180", "Chinese", "岁");
wlist.setWord("AA180", "PinYin", "suì");
wlist.setWord("AA180", "English", "age");
wlist.setWord("AA181", "Chinese", "祝贺");
wlist.setWord("AA181", "PinYin", "zhù hè");
wlist.setWord("AA181", "English", "congratulation");
wlist.setWord("AA182", "Chinese", "舞会");
wlist.setWord("AA182", "PinYin", "wǔ huì");
wlist.setWord("AA182", "English", "party");
wlist.setWord("AA183", "Chinese", "参加");
wlist.setWord("AA183", "PinYin", "cān jiā");
wlist.setWord("AA183", "English", "to attend");
wlist.setWord("AA184", "Chinese", "同学");
wlist.setWord("AA184", "PinYin", "tóng xué");
wlist.setWord("AA184", "English", "classmate");
wlist.setWord("AA185", "Chinese", "一定");
wlist.setWord("AA185", "PinYin", "yī dìng");
wlist.setWord("AA185", "English", "surely");
wlist.setWord("AA186", "Chinese", "有意思");
wlist.setWord("AA186", "PinYin", "yǒu yì si");
wlist.setWord("AA186", "English", "interesting");
wlist.setWord("AA187", "Chinese", "星期");
wlist.setWord("AA187", "PinYin", "xīng qī");
wlist.setWord("AA187", "English", "week");
wlist.setWord("AA188", "Chinese", "星期日");
wlist.setWord("AA188", "PinYin", "xīng qī rì");
wlist.setWord("AA188", "English", "Sunday");
wlist.setWord("AA189", "Chinese", "知道");
wlist.setWord("AA189", "PinYin", "zhī dao");
wlist.setWord("AA189", "English", "to know");
wlist.setWord("AA190", "Chinese", "地址");
wlist.setWord("AA190", "PinYin", "dì zhǐ");
wlist.setWord("AA190", "English", "address");
wlist.setWord("AA191", "Chinese", "年");
wlist.setWord("AA191", "PinYin", "nián");
wlist.setWord("AA191", "English", "year");
wlist.setWord("AA192", "Chinese", "去年");
wlist.setWord("AA192", "PinYin", "qù nián");
wlist.setWord("AA192", "English", "last year");
wlist.setWord("AA193", "Chinese", "明年");
wlist.setWord("AA193", "PinYin", "míng nián");
wlist.setWord("AA193", "English", "next year");
wlist.setWord("AA194", "Chinese", "音乐会");
wlist.setWord("AA194", "PinYin", "yīn yuè huì");
wlist.setWord("AA194", "English", "concert");
wlist.setWord("AA195", "Chinese", "结婚");
wlist.setWord("AA195", "PinYin", "jié hūn");
wlist.setWord("AA195", "English", "to get married");
wlist.setWord("AA196", "Chinese", "对不起");
wlist.setWord("AA196", "PinYin", "duì bu qǐ");
wlist.setWord("AA196", "English", "I'm sorry");
wlist.setWord("AA197", "Chinese", "约会");
wlist.setWord("AA197", "PinYin", "yuē huì");
wlist.setWord("AA197", "English", "appointment");
wlist.setWord("AA198", "Chinese", "没关系");
wlist.setWord("AA198", "PinYin", "méi guān xi");
wlist.setWord("AA198", "English", "it doesn't matter");
wlist.setWord("AA199", "Chinese", "谈");
wlist.setWord("AA199", "PinYin", "tán");
wlist.setWord("AA199", "English", "to chat");
