langs = ["Chinese","English","Pinyin"];

wlist = new WordList();

wlist.setWord("AA2", "Chinese", "束");
wlist.setWord("AA2", "Pinyin", "shù");
wlist.setWord("AA2", "English", "bunch");
wlist.setWord("AA3", "Chinese", "花儿");
wlist.setWord("AA3", "Pinyin", "huār");
wlist.setWord("AA3", "English", "flower");
wlist.setWord("AA4", "Chinese", "真");
wlist.setWord("AA4", "Pinyin", "zhēn");
wlist.setWord("AA4", "English", "real");
wlist.setWord("AA5", "Chinese", "好看");
wlist.setWord("AA5", "Pinyin", "hǎo kàn");
wlist.setWord("AA5", "English", "good-looking");
wlist.setWord("AA6", "Chinese", "祝");
wlist.setWord("AA6", "Pinyin", "zhù");
wlist.setWord("AA6", "English", "to wish");
wlist.setWord("AA7", "Chinese", "送");
wlist.setWord("AA7", "Pinyin", "sòng");
wlist.setWord("AA7", "English", "to give");
wlist.setWord("AA8", "Chinese", "非常");
wlist.setWord("AA8", "Pinyin", "fēi cháng");
wlist.setWord("AA8", "English", "extremely");
wlist.setWord("AA9", "Chinese", "感谢");
wlist.setWord("AA9", "Pinyin", "gǎn xiè");
wlist.setWord("AA9", "English", "to thank");
wlist.setWord("AA10", "Chinese", "高兴");
wlist.setWord("AA10", "Pinyin", "gāo xìng");
wlist.setWord("AA10", "English", "happy");
wlist.setWord("AA11", "Chinese", "太太");
wlist.setWord("AA11", "Pinyin", "tài tai");
wlist.setWord("AA11", "English", "Mrs.");
wlist.setWord("AA12", "Chinese", "年轻");
wlist.setWord("AA12", "Pinyin", "nián qīng");
wlist.setWord("AA12", "English", "young");
wlist.setWord("AA13", "Chinese", "多");
wlist.setWord("AA13", "Pinyin", "duō");
wlist.setWord("AA13", "English", "how");
wlist.setWord("AA14", "Chinese", "跳舞");
wlist.setWord("AA14", "Pinyin", "tiào wǔ");
wlist.setWord("AA14", "English", "to dance");
wlist.setWord("AA15", "Chinese", "姑娘");
wlist.setWord("AA15", "Pinyin", "gū niang");
wlist.setWord("AA15", "English", "girl");
wlist.setWord("AA16", "Chinese", "漂亮");
wlist.setWord("AA16", "Pinyin", "piào liang");
wlist.setWord("AA16", "English", "beautiful");
wlist.setWord("AA17", "Chinese", "更");
wlist.setWord("AA17", "Pinyin", "gèng");
wlist.setWord("AA17", "English", "still");
wlist.setWord("AA18", "Chinese", "象");
wlist.setWord("AA18", "Pinyin", "xiàng");
wlist.setWord("AA18", "English", "to resemble");
wlist.setWord("AA19", "Chinese", "开");
wlist.setWord("AA19", "Pinyin", "kāi");
wlist.setWord("AA19", "English", "open");
wlist.setWord("AA20", "Chinese", "门");
wlist.setWord("AA20", "Pinyin", "mén");
wlist.setWord("AA20", "English", "door");
wlist.setWord("AA21", "Chinese", "日本");
wlist.setWord("AA21", "Pinyin", "Rì běn");
wlist.setWord("AA21", "English", "Japan");
wlist.setWord("AA22", "Chinese", "干净");
wlist.setWord("AA22", "Pinyin", "gān jing");
wlist.setWord("AA22", "English", "clean");
wlist.setWord("AA23", "Chinese", "新年");
wlist.setWord("AA23", "Pinyin", "xīn nián");
wlist.setWord("AA23", "English", "New Year");
wlist.setWord("AA24", "Chinese", "岁数");
wlist.setWord("AA24", "Pinyin", "suì shu");
wlist.setWord("AA24", "English", "age");
wlist.setWord("AA25", "Chinese", "礼物");
wlist.setWord("AA25", "Pinyin", "lǐ wù");
wlist.setWord("AA25", "English", "gift");
wlist.setWord("AA26", "Chinese", "照片");
wlist.setWord("AA26", "Pinyin", "zhào piàn");
wlist.setWord("AA26", "English", "picture");
wlist.setWord("AA27", "Chinese", "儿子");
wlist.setWord("AA27", "Pinyin", "ér zi");
wlist.setWord("AA27", "English", "son");
wlist.setWord("AA28", "Chinese", "女儿");
wlist.setWord("AA28", "Pinyin", "nǚ ér");
wlist.setWord("AA28", "English", "daughter");
wlist.setWord("AA29", "Chinese", "后边");
wlist.setWord("AA29", "Pinyin", "hòu biān");
wlist.setWord("AA29", "English", "behind");
wlist.setWord("AA30", "Chinese", "小");
wlist.setWord("AA30", "Pinyin", "xiǎo");
wlist.setWord("AA30", "English", "little/small");
wlist.setWord("AA31", "Chinese", "花园");
wlist.setWord("AA31", "Pinyin", "huā yuán");
wlist.setWord("AA31", "English", "garden");
wlist.setWord("AA32", "Chinese", "房子");
wlist.setWord("AA32", "Pinyin", "fáng zi");
wlist.setWord("AA32", "English", "house");
wlist.setWord("AA33", "Chinese", "客厅");
wlist.setWord("AA33", "Pinyin", "kè tīng");
wlist.setWord("AA33", "English", "drawing room");
wlist.setWord("AA34", "Chinese", "旁边");
wlist.setWord("AA34", "Pinyin", "páng biān");
wlist.setWord("AA34", "English", "side");
wlist.setWord("AA35", "Chinese", "书房");
wlist.setWord("AA35", "Pinyin", "shū fáng");
wlist.setWord("AA35", "English", "study room");
wlist.setWord("AA36", "Chinese", "椅子");
wlist.setWord("AA36", "Pinyin", "yǐ zi");
wlist.setWord("AA36", "English", "chair");
wlist.setWord("AA37", "Chinese", "少");
wlist.setWord("AA37", "Pinyin", "shǎo");
wlist.setWord("AA37", "English", "few");
wlist.setWord("AA38", "Chinese", "桌子");
wlist.setWord("AA38", "Pinyin", "zhuō zi");
wlist.setWord("AA38", "English", "table");
wlist.setWord("AA39", "Chinese", "上边");
wlist.setWord("AA39", "Pinyin", "shàng bian");
wlist.setWord("AA39", "English", "above");
wlist.setWord("AA40", "Chinese", "总是");
wlist.setWord("AA40", "Pinyin", "zǒng shì");
wlist.setWord("AA40", "English", "always");
wlist.setWord("AA41", "Chinese", "总");
wlist.setWord("AA41", "Pinyin", "zǒng");
wlist.setWord("AA41", "English", "always");
wlist.setWord("AA42", "Chinese", "整理");
wlist.setWord("AA42", "Pinyin", "zhěng lǐ");
wlist.setWord("AA42", "English", "to arrange");
wlist.setWord("AA43", "Chinese", "厨房");
wlist.setWord("AA43", "Pinyin", "chú fáng");
wlist.setWord("AA43", "English", "kitchen");
wlist.setWord("AA44", "Chinese", "对面");
wlist.setWord("AA44", "Pinyin", "duì miàn");
wlist.setWord("AA44", "English", "opposite");
wlist.setWord("AA45", "Chinese", "帮助");
wlist.setWord("AA45", "Pinyin", "bāng zhù");
wlist.setWord("AA45", "English", "to help");
wlist.setWord("AA46", "Chinese", "帮");
wlist.setWord("AA46", "Pinyin", "bāng");
wlist.setWord("AA46", "English", "to help");
wlist.setWord("AA47", "Chinese", "餐厅");
wlist.setWord("AA47", "Pinyin", "cān tīng");
wlist.setWord("AA47", "English", "dining-hall");
wlist.setWord("AA48", "Chinese", "左边");
wlist.setWord("AA48", "Pinyin", "zuǒ biān");
wlist.setWord("AA48", "English", "left");
wlist.setWord("AA49", "Chinese", "里边");
wlist.setWord("AA49", "Pinyin", "lǐ biān");
wlist.setWord("AA49", "English", "inside");
wlist.setWord("AA50", "Chinese", "房间");
wlist.setWord("AA50", "Pinyin", "fáng jiān");
wlist.setWord("AA50", "English", "room");
wlist.setWord("AA51", "Chinese", "卧室");
wlist.setWord("AA51", "Pinyin", "wò shì");
wlist.setWord("AA51", "English", "bedroom");
wlist.setWord("AA52", "Chinese", "洗澡间");
wlist.setWord("AA52", "Pinyin", "xǐ zǎo jiān");
wlist.setWord("AA52", "English", "bathroom");
wlist.setWord("AA53", "Chinese", "洗澡");
wlist.setWord("AA53", "Pinyin", "xǐ zǎo");
wlist.setWord("AA53", "English", "to take a bath");
wlist.setWord("AA54", "Chinese", "怎么样");
wlist.setWord("AA54", "Pinyin", "zěn me yàng");
wlist.setWord("AA54", "English", "how");
wlist.setWord("AA55", "Chinese", "外边");
wlist.setWord("AA55", "Pinyin", "wài biān");
wlist.setWord("AA55", "English", "outside");
wlist.setWord("AA56", "Chinese", "下边");
wlist.setWord("AA56", "Pinyin", "xià biān");
wlist.setWord("AA56", "English", "below");
wlist.setWord("AA57", "Chinese", "前边");
wlist.setWord("AA57", "Pinyin", "qián biān");
wlist.setWord("AA57", "English", "front");
wlist.setWord("AA58", "Chinese", "右边");
wlist.setWord("AA58", "Pinyin", "yòu biān");
wlist.setWord("AA58", "English", "right");
wlist.setWord("AA59", "Chinese", "中间");
wlist.setWord("AA59", "Pinyin", "zhōng jiān");
wlist.setWord("AA59", "English", "middle");
wlist.setWord("AA60", "Chinese", "窗户");
wlist.setWord("AA60", "Pinyin", "chuāng hu");
wlist.setWord("AA60", "English", "window");
wlist.setWord("AA61", "Chinese", "正在");
wlist.setWord("AA61", "Pinyin", "zhèng zài");
wlist.setWord("AA61", "English", "while");
wlist.setWord("AA62", "Chinese", "电视");
wlist.setWord("AA62", "Pinyin", "diàn shì");
wlist.setWord("AA62", "English", "television");
wlist.setWord("AA63", "Chinese", "接");
wlist.setWord("AA63", "Pinyin", "jiē");
wlist.setWord("AA63", "English", "to answer");
wlist.setWord("AA64", "Chinese", "电话");
wlist.setWord("AA64", "Pinyin", "diàn huà");
wlist.setWord("AA64", "English", "telephone");
wlist.setWord("AA65", "Chinese", "没有");
wlist.setWord("AA65", "Pinyin", "méi yǒu");
wlist.setWord("AA65", "English", "not");
wlist.setWord("AA66", "Chinese", "复习");
wlist.setWord("AA66", "Pinyin", "fù xí");
wlist.setWord("AA66", "English", "to review");
wlist.setWord("AA67", "Chinese", "课文");
wlist.setWord("AA67", "Pinyin", "kè wén");
wlist.setWord("AA67", "English", "text");
wlist.setWord("AA68", "Chinese", "新闻");
wlist.setWord("AA68", "Pinyin", "xīn wén");
wlist.setWord("AA68", "English", "news");
wlist.setWord("AA69", "Chinese", "友好");
wlist.setWord("AA69", "Pinyin", "yǒu hǎo");
wlist.setWord("AA69", "English", "friendly");
wlist.setWord("AA70", "Chinese", "代表团");
wlist.setWord("AA70", "Pinyin", "dài biǎo tuán");
wlist.setWord("AA70", "English", "delegation");
wlist.setWord("AA71", "Chinese", "代表");
wlist.setWord("AA71", "Pinyin", "dài biǎo");
wlist.setWord("AA71", "English", "representative");
wlist.setWord("AA72", "Chinese", "参观");
wlist.setWord("AA72", "Pinyin", "cān guān");
wlist.setWord("AA72", "English", "to visit");
wlist.setWord("AA73", "Chinese", "工厂");
wlist.setWord("AA73", "Pinyin", "gōng chǎng");
wlist.setWord("AA73", "English", "factory");
wlist.setWord("AA74", "Chinese", "工人");
wlist.setWord("AA74", "Pinyin", "gōng rén");
wlist.setWord("AA74", "English", "worker");
wlist.setWord("AA75", "Chinese", "访问");
wlist.setWord("AA75", "Pinyin", "fǎng wèn");
wlist.setWord("AA75", "English", "to call on");
wlist.setWord("AA76", "Chinese", "照片");
wlist.setWord("AA76", "Pinyin", "zhào piàn");
wlist.setWord("AA76", "English", "photo");
wlist.setWord("AA77", "Chinese", "明天");
wlist.setWord("AA77", "Pinyin", "míng tiān");
wlist.setWord("AA77", "English", "tomorrow");
wlist.setWord("AA78", "Chinese", "城");
wlist.setWord("AA78", "Pinyin", "chéng");
wlist.setWord("AA78", "English", "city");
wlist.setWord("AA79", "Chinese", "外边");
wlist.setWord("AA79", "Pinyin", "wài biān");
wlist.setWord("AA79", "English", "outside");
wlist.setWord("AA80", "Chinese", "玩儿");
wlist.setWord("AA80", "Pinyin", "wánr");
wlist.setWord("AA80", "English", "to play");
wlist.setWord("AA81", "Chinese", "出发");
wlist.setWord("AA81", "Pinyin", "chū fā");
wlist.setWord("AA81", "English", "to start out");
wlist.setWord("AA82", "Chinese", "开车");
wlist.setWord("AA82", "Pinyin", "kāi chē");
wlist.setWord("AA82", "English", "to drive a car");
wlist.setWord("AA83", "Chinese", "接人");
wlist.setWord("AA83", "Pinyin", "jiē rén");
wlist.setWord("AA83", "English", "to meet a person");
wlist.setWord("AA84", "Chinese", "号码");
wlist.setWord("AA84", "Pinyin", "hào mǎ");
wlist.setWord("AA84", "English", "number");
wlist.setWord("AA85", "Chinese", "点心");
wlist.setWord("AA85", "Pinyin", "diǎn xīn");
wlist.setWord("AA85", "English", "pastry");
wlist.setWord("AA86", "Chinese", "农村");
wlist.setWord("AA86", "Pinyin", "nóng cūn");
wlist.setWord("AA86", "English", "countryside");
wlist.setWord("AA87", "Chinese", "农民");
wlist.setWord("AA87", "Pinyin", "nóng mín");
wlist.setWord("AA87", "English", "peasant");
wlist.setWord("AA88", "Chinese", "火车");
wlist.setWord("AA88", "Pinyin", "huǒ chē");
wlist.setWord("AA88", "English", "train");
wlist.setWord("AA89", "Chinese", "锻炼");
wlist.setWord("AA89", "Pinyin", "duàn liàn");
wlist.setWord("AA89", "English", "to do physical training");
wlist.setWord("AA90", "Chinese", "回答");
wlist.setWord("AA90", "Pinyin", "huí dá");
wlist.setWord("AA90", "English", "to reply");
wlist.setWord("AA91", "Chinese", "些");
wlist.setWord("AA91", "Pinyin", "xiē");
wlist.setWord("AA91", "English", "some");
wlist.setWord("AA92", "Chinese", "难");
wlist.setWord("AA92", "Pinyin", "nán");
wlist.setWord("AA92", "English", "difficult");
wlist.setWord("AA93", "Chinese", "生词");
wlist.setWord("AA93", "Pinyin", "shēng cí");
wlist.setWord("AA93", "English", "new word");
wlist.setWord("AA94", "Chinese", "词");
wlist.setWord("AA94", "Pinyin", "cí");
wlist.setWord("AA94", "English", "word");
wlist.setWord("AA95", "Chinese", "念");
wlist.setWord("AA95", "Pinyin", "niàn");
wlist.setWord("AA95", "English", "to read aloud");
wlist.setWord("AA96", "Chinese", "练习");
wlist.setWord("AA96", "Pinyin", "liàn xí");
wlist.setWord("AA96", "English", "to practise");
wlist.setWord("AA97", "Chinese", "认真");
wlist.setWord("AA97", "Pinyin", "rèn zhēn");
wlist.setWord("AA97", "English", "serious");
wlist.setWord("AA98", "Chinese", "懂");
wlist.setWord("AA98", "Pinyin", "dǒng");
wlist.setWord("AA98", "English", "to understand");
wlist.setWord("AA99", "Chinese", "晚");
wlist.setWord("AA99", "Pinyin", "wǎn");
wlist.setWord("AA99", "English", "late");
wlist.setWord("AA100", "Chinese", "停");
wlist.setWord("AA100", "Pinyin", "tíng");
wlist.setWord("AA100", "English", "to stop");
wlist.setWord("AA101", "Chinese", "河");
wlist.setWord("AA101", "Pinyin", "hé");
wlist.setWord("AA101", "English", "river");
wlist.setWord("AA102", "Chinese", "游泳");
wlist.setWord("AA102", "Pinyin", "yóu yǒng");
wlist.setWord("AA102", "English", "to swim");
wlist.setWord("AA103", "Chinese", "准备");
wlist.setWord("AA103", "Pinyin", "zhǔn bèi");
wlist.setWord("AA103", "English", "to prepare");
wlist.setWord("AA104", "Chinese", "钓");
wlist.setWord("AA104", "Pinyin", "diào");
wlist.setWord("AA104", "English", "to fish");
wlist.setWord("AA105", "Chinese", "鱼");
wlist.setWord("AA105", "Pinyin", "yú");
wlist.setWord("AA105", "English", "fish");
wlist.setWord("AA106", "Chinese", "汤");
wlist.setWord("AA106", "Pinyin", "tāng");
wlist.setWord("AA106", "English", "soup");
wlist.setWord("AA107", "Chinese", "快");
wlist.setWord("AA107", "Pinyin", "kuài");
wlist.setWord("AA107", "English", "fast");
wlist.setWord("AA108", "Chinese", "哪里");
wlist.setWord("AA108", "Pinyin", "nǎ li");
wlist.setWord("AA108", "English", "it is nothing");
wlist.setWord("AA109", "Chinese", "慢");
wlist.setWord("AA109", "Pinyin", "màn");
wlist.setWord("AA109", "English", "slow");
wlist.setWord("AA110", "Chinese", "教练");
wlist.setWord("AA110", "Pinyin", "jiào liàn");
wlist.setWord("AA110", "English", "coach");
wlist.setWord("AA111", "Chinese", "不错");
wlist.setWord("AA111", "Pinyin", "bú cuò");
wlist.setWord("AA111", "English", "pretty good");
wlist.setWord("AA112", "Chinese", "面包");
wlist.setWord("AA112", "Pinyin", "miàn bāo");
wlist.setWord("AA112", "English", "bread");
wlist.setWord("AA113", "Chinese", "火腿");
wlist.setWord("AA113", "Pinyin", "huǒ tuǐ");
wlist.setWord("AA113", "English", "ham");
wlist.setWord("AA114", "Chinese", "一点儿");
wlist.setWord("AA114", "Pinyin", "yī diǎnr");
wlist.setWord("AA114", "English", "a little");
wlist.setWord("AA115", "Chinese", "奶酪");
wlist.setWord("AA115", "Pinyin", "nǎi lào");
wlist.setWord("AA115", "English", "cheese");
wlist.setWord("AA116", "Chinese", "再");
wlist.setWord("AA116", "Pinyin", "zài");
wlist.setWord("AA116", "English", "again");
wlist.setWord("AA117", "Chinese", "矿泉水");
wlist.setWord("AA117", "Pinyin", "kuàng quán shuǐ");
wlist.setWord("AA117", "English", "mineral water");
wlist.setWord("AA118", "Chinese", "清楚");
wlist.setWord("AA118", "Pinyin", "qīng chu");
wlist.setWord("AA118", "English", "clear");
wlist.setWord("AA119", "Chinese", "流利");
wlist.setWord("AA119", "Pinyin", "liú lì");
wlist.setWord("AA119", "English", "fluent");
wlist.setWord("AA120", "Chinese", "整齐");
wlist.setWord("AA120", "Pinyin", "zhěng qí");
wlist.setWord("AA120", "English", "tidy");
wlist.setWord("AA121", "Chinese", "菜");
wlist.setWord("AA121", "Pinyin", "cài");
wlist.setWord("AA121", "English", "dish");
wlist.setWord("AA122", "Chinese", "牛奶");
wlist.setWord("AA122", "Pinyin", "niú nǎi");
wlist.setWord("AA122", "English", "milk");
wlist.setWord("AA123", "Chinese", "比较");
wlist.setWord("AA123", "Pinyin", "bǐ jiào");
wlist.setWord("AA123", "English", "to compare");
wlist.setWord("AA124", "Chinese", "研究");
wlist.setWord("AA124", "Pinyin", "yán jiū");
wlist.setWord("AA124", "English", "to research");
wlist.setWord("AA125", "Chinese", "文学");
wlist.setWord("AA125", "Pinyin", "wén xué");
wlist.setWord("AA125", "English", "literature");
wlist.setWord("AA126", "Chinese", "早");
wlist.setWord("AA126", "Pinyin", "zǎo");
wlist.setWord("AA126", "English", "early");
wlist.setWord("AA127", "Chinese", "谈");
wlist.setWord("AA127", "Pinyin", "tán");
wlist.setWord("AA127", "English", "to talk");
wlist.setWord("AA128", "Chinese", "会");
wlist.setWord("AA128", "Pinyin", "huì");
wlist.setWord("AA128", "English", "can");
wlist.setWord("AA129", "Chinese", "当");
wlist.setWord("AA129", "Pinyin", "dāng");
wlist.setWord("AA129", "English", "to act as");
wlist.setWord("AA130", "Chinese", "翻译");
wlist.setWord("AA130", "Pinyin", "fān yì");
wlist.setWord("AA130", "English", "interpreter");
wlist.setWord("AA131", "Chinese", "能");
wlist.setWord("AA131", "Pinyin", "néng");
wlist.setWord("AA131", "English", "to be able");
wlist.setWord("AA132", "Chinese", "加深");
wlist.setWord("AA132", "Pinyin", "jiā shēn");
wlist.setWord("AA132", "English", "to deepen");
wlist.setWord("AA133", "Chinese", "人民");
wlist.setWord("AA133", "Pinyin", "rén mín");
wlist.setWord("AA133", "English", "people");
wlist.setWord("AA134", "Chinese", "了解");
wlist.setWord("AA134", "Pinyin", "liǎo jiě");
wlist.setWord("AA134", "English", "to understand");
wlist.setWord("AA135", "Chinese", "有名");
wlist.setWord("AA135", "Pinyin", "yǒu míng");
wlist.setWord("AA135", "English", "famous");
wlist.setWord("AA136", "Chinese", "作家");
wlist.setWord("AA136", "Pinyin", "zuò jiā");
wlist.setWord("AA136", "English", "author");
wlist.setWord("AA137", "Chinese", "或者");
wlist.setWord("AA137", "Pinyin", "huò zhě");
wlist.setWord("AA137", "English", "maybe");
wlist.setWord("AA138", "Chinese", "就");
wlist.setWord("AA138", "Pinyin", "jiù");
wlist.setWord("AA138", "English", "at once");
wlist.setWord("AA139", "Chinese", "应该");
wlist.setWord("AA139", "Pinyin", "yīng gāi");
wlist.setWord("AA139", "English", "should");
wlist.setWord("AA140", "Chinese", "俩");
wlist.setWord("AA140", "Pinyin", "liǎ");
wlist.setWord("AA140", "English", "both");
wlist.setWord("AA141", "Chinese", "可以");
wlist.setWord("AA141", "Pinyin", "kě yǐ");
wlist.setWord("AA141", "English", "may/can");
wlist.setWord("AA142", "Chinese", "理想");
wlist.setWord("AA142", "Pinyin", "lǐ xiǎng");
wlist.setWord("AA142", "English", "ideal");
wlist.setWord("AA143", "Chinese", "可是");
wlist.setWord("AA143", "Pinyin", "kě shì");
wlist.setWord("AA143", "English", "but/however");
wlist.setWord("AA144", "Chinese", "容易");
wlist.setWord("AA144", "Pinyin", "róng yì");
wlist.setWord("AA144", "English", "easy");
wlist.setWord("AA145", "Chinese", "成语");
wlist.setWord("AA145", "Pinyin", "chéng yǔ");
wlist.setWord("AA145", "English", "proverb");
wlist.setWord("AA146", "Chinese", "歌剧");
wlist.setWord("AA146", "Pinyin", "gē jù");
wlist.setWord("AA146", "English", "opera");
wlist.setWord("AA147", "Chinese", "小说");
wlist.setWord("AA147", "Pinyin", "xiǎo shuō");
wlist.setWord("AA147", "English", "novel");
wlist.setWord("AA148", "Chinese", "诗歌");
wlist.setWord("AA148", "Pinyin", "shī gē");
wlist.setWord("AA148", "English", "poem");
wlist.setWord("AA149", "Chinese", "画");
wlist.setWord("AA149", "Pinyin", "huà");
wlist.setWord("AA149", "English", "to draw");
wlist.setWord("AA150", "Chinese", "画儿");
wlist.setWord("AA150", "Pinyin", "huàr");
wlist.setWord("AA150", "English", "drawing");
wlist.setWord("AA151", "Chinese", "晚饭");
wlist.setWord("AA151", "Pinyin", "wǎn fàn");
wlist.setWord("AA151", "English", "supper");
wlist.setWord("AA152", "Chinese", "进来");
wlist.setWord("AA152", "Pinyin", "jìn lái");
wlist.setWord("AA152", "English", "to enter");
wlist.setWord("AA153", "Chinese", "开始");
wlist.setWord("AA153", "Pinyin", "kāi shǐ");
wlist.setWord("AA153", "English", "to begin");
wlist.setWord("AA154", "Chinese", "大使馆");
wlist.setWord("AA154", "Pinyin", "dà shǐ guǎn");
wlist.setWord("AA154", "English", "embassy");
wlist.setWord("AA155", "Chinese", "大使");
wlist.setWord("AA155", "Pinyin", "dà shǐ");
wlist.setWord("AA155", "English", "ambassador");
wlist.setWord("AA156", "Chinese", "招待会");
wlist.setWord("AA156", "Pinyin", "zhāo dài huì");
wlist.setWord("AA156", "English", "reception");
wlist.setWord("AA157", "Chinese", "酒");
wlist.setWord("AA157", "Pinyin", "jiǔ");
wlist.setWord("AA157", "English", "alcohol");
wlist.setWord("AA158", "Chinese", "尝");
wlist.setWord("AA158", "Pinyin", "cháng");
wlist.setWord("AA158", "English", "to taste");
wlist.setWord("AA159", "Chinese", "为");
wlist.setWord("AA159", "Pinyin", "wèi");
wlist.setWord("AA159", "English", "for/to");
wlist.setWord("AA160", "Chinese", "健康");
wlist.setWord("AA160", "Pinyin", "jiàn kāng");
wlist.setWord("AA160", "English", "health");
wlist.setWord("AA161", "Chinese", "干杯");
wlist.setWord("AA161", "Pinyin", "gān bēi");
wlist.setWord("AA161", "English", "to drink a toast");
wlist.setWord("AA162", "Chinese", "友谊");
wlist.setWord("AA162", "Pinyin", "yǒu yì");
wlist.setWord("AA162", "English", "friendship");
wlist.setWord("AA163", "Chinese", "葡萄酒");
wlist.setWord("AA163", "Pinyin", "pú táo jiǔ");
wlist.setWord("AA163", "English", "grape wine");
wlist.setWord("AA164", "Chinese", "葡萄");
wlist.setWord("AA164", "Pinyin", "pú tao");
wlist.setWord("AA164", "English", "grape");
wlist.setWord("AA165", "Chinese", "菜");
wlist.setWord("AA165", "Pinyin", "cài");
wlist.setWord("AA165", "English", "dish");
wlist.setWord("AA166", "Chinese", "筷子");
wlist.setWord("AA166", "Pinyin", "kuài zi");
wlist.setWord("AA166", "English", "chopsticks");
wlist.setWord("AA167", "Chinese", "试");
wlist.setWord("AA167", "Pinyin", "shì");
wlist.setWord("AA167", "English", "to try");
wlist.setWord("AA168", "Chinese", "文化");
wlist.setWord("AA168", "Pinyin", "wén huà");
wlist.setWord("AA168", "English", "culture");
wlist.setWord("AA169", "Chinese", "夫人");
wlist.setWord("AA169", "Pinyin", "fū ren");
wlist.setWord("AA169", "English", "Mrs.");
wlist.setWord("AA170", "Chinese", "又");
wlist.setWord("AA170", "Pinyin", "yòu");
wlist.setWord("AA170", "English", "again");
wlist.setWord("AA171", "Chinese", "大家");
wlist.setWord("AA171", "Pinyin", "dà jiā");
wlist.setWord("AA171", "English", "everybody");
wlist.setWord("AA172", "Chinese", "到");
wlist.setWord("AA172", "Pinyin", "dào");
wlist.setWord("AA172", "English", "to arrive");
wlist.setWord("AA173", "Chinese", "楼");
wlist.setWord("AA173", "Pinyin", "lóu");
wlist.setWord("AA173", "English", "floor");
wlist.setWord("AA174", "Chinese", "病");
wlist.setWord("AA174", "Pinyin", "bìng");
wlist.setWord("AA174", "English", "illness");
wlist.setWord("AA175", "Chinese", "小学生");
wlist.setWord("AA175", "Pinyin", "xiǎo xué shēng");
wlist.setWord("AA175", "English", "pupil");
wlist.setWord("AA176", "Chinese", "足球");
wlist.setWord("AA176", "Pinyin", "zú qiú");
wlist.setWord("AA176", "English", "football");
wlist.setWord("AA177", "Chinese", "球");
wlist.setWord("AA177", "Pinyin", "qiú");
wlist.setWord("AA177", "English", "ball");
wlist.setWord("AA178", "Chinese", "赛");
wlist.setWord("AA178", "Pinyin", "sài");
wlist.setWord("AA178", "English", "competition");
wlist.setWord("AA179", "Chinese", "昨天");
wlist.setWord("AA179", "Pinyin", "zuó tiān");
wlist.setWord("AA179", "English", "yesterday");
wlist.setWord("AA180", "Chinese", "办");
wlist.setWord("AA180", "Pinyin", "bàn");
wlist.setWord("AA180", "English", "to handle");
wlist.setWord("AA181", "Chinese", "签证");
wlist.setWord("AA181", "Pinyin", "qiān zhèng");
wlist.setWord("AA181", "English", "visa");
wlist.setWord("AA182", "Chinese", "午饭");
wlist.setWord("AA182", "Pinyin", "wǔ fàn");
wlist.setWord("AA182", "English", "lunch");
wlist.setWord("AA183", "Chinese", "队");
wlist.setWord("AA183", "Pinyin", "duì");
wlist.setWord("AA183", "English", "team");
wlist.setWord("AA184", "Chinese", "赢");
wlist.setWord("AA184", "Pinyin", "yíng");
wlist.setWord("AA184", "English", "to win");
wlist.setWord("AA185", "Chinese", "输");
wlist.setWord("AA185", "Pinyin", "shū");
wlist.setWord("AA185", "English", "to lose");
wlist.setWord("AA186", "Chinese", "公平");
wlist.setWord("AA186", "Pinyin", "gōng píng");
wlist.setWord("AA186", "English", "fair");
wlist.setWord("AA187", "Chinese", "踢");
wlist.setWord("AA187", "Pinyin", "tī");
wlist.setWord("AA187", "English", "to kick");
wlist.setWord("AA188", "Chinese", "行李");
wlist.setWord("AA188", "Pinyin", "xíng li");
wlist.setWord("AA188", "English", "luggage");
wlist.setWord("AA189", "Chinese", "箱子");
wlist.setWord("AA189", "Pinyin", "xiāng zi");
wlist.setWord("AA189", "English", "suitcase");
wlist.setWord("AA190", "Chinese", "帽子");
wlist.setWord("AA190", "Pinyin", "mào zi");
wlist.setWord("AA190", "English", "hat");
wlist.setWord("AA191", "Chinese", "双");
wlist.setWord("AA191", "Pinyin", "shuāng");
wlist.setWord("AA191", "English", "pair");
wlist.setWord("AA192", "Chinese", "冰鞋");
wlist.setWord("AA192", "Pinyin", "bīng xié");
wlist.setWord("AA192", "English", "skates");
wlist.setWord("AA193", "Chinese", "鞋");
wlist.setWord("AA193", "Pinyin", "xié");
wlist.setWord("AA193", "English", "shoes");
wlist.setWord("AA194", "Chinese", "冬天");
wlist.setWord("AA194", "Pinyin", "dōng tiān");
wlist.setWord("AA194", "English", "winter");
wlist.setWord("AA195", "Chinese", "滑冰");
wlist.setWord("AA195", "Pinyin", "huá bīng");
wlist.setWord("AA195", "English", "to skate");
wlist.setWord("AA196", "Chinese", "早饭");
wlist.setWord("AA196", "Pinyin", "zǎo fàn");
wlist.setWord("AA196", "English", "breakfast");
wlist.setWord("AA197", "Chinese", "体育场");
wlist.setWord("AA197", "Pinyin", "tǐ yù chǎng");
wlist.setWord("AA197", "English", "stadium");
wlist.setWord("AA198", "Chinese", "公园");
wlist.setWord("AA198", "Pinyin", "gōng yuán");
wlist.setWord("AA198", "English", "park");
wlist.setWord("AA199", "Chinese", "运动");
wlist.setWord("AA199", "Pinyin", "yùn dòng");
wlist.setWord("AA199", "English", "sports");
wlist.setWord("AA200", "Chinese", "篮球");
wlist.setWord("AA200", "Pinyin", "lán qiú");
wlist.setWord("AA200", "English", "basketball");
wlist.setWord("AA201", "Chinese", "排球");
wlist.setWord("AA201", "Pinyin", "pái qiú");
wlist.setWord("AA201", "English", "volleyball");
wlist.setWord("AA202", "Chinese", "滑雪");
wlist.setWord("AA202", "Pinyin", "huá xuě");
wlist.setWord("AA202", "English", "to ski");
wlist.setWord("AA203", "Chinese", "飞机");
wlist.setWord("AA203", "Pinyin", "fēi jī");
wlist.setWord("AA203", "English", "aeroplane");
wlist.setWord("AA204", "Chinese", "起飞");
wlist.setWord("AA204", "Pinyin", "qǐ fēi");
wlist.setWord("AA204", "English", "to take off");
wlist.setWord("AA205", "Chinese", "机场");
wlist.setWord("AA205", "Pinyin", "jī chǎng");
wlist.setWord("AA205", "English", "airport");
wlist.setWord("AA206", "Chinese", "分别");
wlist.setWord("AA206", "Pinyin", "fēn bié");
wlist.setWord("AA206", "English", "to separate");
wlist.setWord("AA207", "Chinese", "愿意");
wlist.setWord("AA207", "Pinyin", "yuàn yì");
wlist.setWord("AA207", "English", "to be willing");
wlist.setWord("AA208", "Chinese", "离开");
wlist.setWord("AA208", "Pinyin", "lí kāi");
wlist.setWord("AA208", "English", "to leave");
wlist.setWord("AA209", "Chinese", "见面");
wlist.setWord("AA209", "Pinyin", "jiàn miàn");
wlist.setWord("AA209", "English", "to meet each other");
wlist.setWord("AA210", "Chinese", "见");
wlist.setWord("AA210", "Pinyin", "jiàn");
wlist.setWord("AA210", "English", "to meet");
wlist.setWord("AA211", "Chinese", "所以");
wlist.setWord("AA211", "Pinyin", "suǒ yǐ");
wlist.setWord("AA211", "English", "therefore");
wlist.setWord("AA212", "Chinese", "进步");
wlist.setWord("AA212", "Pinyin", "jìn bù");
wlist.setWord("AA212", "English", "to progress");
wlist.setWord("AA213", "Chinese", "努力");
wlist.setWord("AA213", "Pinyin", "nǔ lì");
wlist.setWord("AA213", "English", "hard-working/studious");
wlist.setWord("AA214", "Chinese", "照相");
wlist.setWord("AA214", "Pinyin", "zhào xiàng");
wlist.setWord("AA214", "English", "take a picture");
wlist.setWord("AA215", "Chinese", "站");
wlist.setWord("AA215", "Pinyin", "zhàn");
wlist.setWord("AA215", "English", "to stand");
wlist.setWord("AA216", "Chinese", "紧");
wlist.setWord("AA216", "Pinyin", "jǐn");
wlist.setWord("AA216", "English", "tight");
wlist.setWord("AA217", "Chinese", "上");
wlist.setWord("AA217", "Pinyin", "shàng");
wlist.setWord("AA217", "English", "to board");
wlist.setWord("AA218", "Chinese", "注意");
wlist.setWord("AA218", "Pinyin", "zhù yì");
wlist.setWord("AA218", "English", "to pay attention to");
wlist.setWord("AA219", "Chinese", "身体");
wlist.setWord("AA219", "Pinyin", "shēn tǐ");
wlist.setWord("AA219", "English", "health");
wlist.setWord("AA220", "Chinese", "放心");
wlist.setWord("AA220", "Pinyin", "fàng xīn");
wlist.setWord("AA220", "English", "to be at ease");
wlist.setWord("AA221", "Chinese", "忘");
wlist.setWord("AA221", "Pinyin", "wàng");
wlist.setWord("AA221", "English", "to forget");
wlist.setWord("AA222", "Chinese", "难过");
wlist.setWord("AA222", "Pinyin", "nán guò");
wlist.setWord("AA222", "English", "sad");
wlist.setWord("AA223", "Chinese", "明年");
wlist.setWord("AA223", "Pinyin", "míng nián");
wlist.setWord("AA223", "English", "next year");
wlist.setWord("AA224", "Chinese", "夏天");
wlist.setWord("AA224", "Pinyin", "xià tiān");
wlist.setWord("AA224", "English", "summer");
wlist.setWord("AA225", "Chinese", "秋天");
wlist.setWord("AA225", "Pinyin", "qiū tiān");
wlist.setWord("AA225", "English", "autumn");
wlist.setWord("AA226", "Chinese", "一路平安");
wlist.setWord("AA226", "Pinyin", "yí lù píng ān");
wlist.setWord("AA226", "English", "bon voyage");
wlist.setWord("AA227", "Chinese", "船");
wlist.setWord("AA227", "Pinyin", "chuán");
wlist.setWord("AA227", "English", "ship");
wlist.setWord("AA228", "Chinese", "送行");
wlist.setWord("AA228", "Pinyin", "sòng xíng");
wlist.setWord("AA228", "English", "to see someone off");
wlist.setWord("AA229", "Chinese", "旅行");
wlist.setWord("AA229", "Pinyin", "lǚ xíng");
wlist.setWord("AA229", "English", "to travel");
wlist.setWord("AA230", "Chinese", "笑");
wlist.setWord("AA230", "Pinyin", "xiào");
wlist.setWord("AA230", "English", "to smile");
wlist.setWord("AA231", "Chinese", "心");
wlist.setWord("AA231", "Pinyin", "xīn");
wlist.setWord("AA231", "English", "heart");
wlist.setWord("AA232", "Chinese", "送");
wlist.setWord("AA232", "Pinyin", "sòng");
wlist.setWord("AA232", "English", "to see someone off");
wlist.setWord("AA233", "Chinese", "女儿");
wlist.setWord("AA233", "Pinyin", "nǚ ér");
wlist.setWord("AA233", "English", "daughter");
wlist.setWord("AA234", "Chinese", "去年");
wlist.setWord("AA234", "Pinyin", "qù nián");
wlist.setWord("AA234", "English", "last year");
wlist.setWord("AA235", "Chinese", "东西");
wlist.setWord("AA235", "Pinyin", "dōng xi");
wlist.setWord("AA235", "English", "thing");
wlist.setWord("AA236", "Chinese", "哭");
wlist.setWord("AA236", "Pinyin", "kū");
wlist.setWord("AA236", "English", "to cry");
wlist.setWord("AA237", "Chinese", "离");
wlist.setWord("AA237", "Pinyin", "lí");
wlist.setWord("AA237", "English", "to leave");
wlist.setWord("AA238", "Chinese", "远");
wlist.setWord("AA238", "Pinyin", "yuǎn");
wlist.setWord("AA238", "English", "distant");
wlist.setWord("AA239", "Chinese", "热情");
wlist.setWord("AA239", "Pinyin", "rè qíng");
wlist.setWord("AA239", "English", "enthusiastic");
wlist.setWord("AA240", "Chinese", "自己");
wlist.setWord("AA240", "Pinyin", "zì jǐ");
wlist.setWord("AA240", "English", "self");
