langs = ["English","Russian","name"];

wlist = new WordList();

wlist.setWord("ah", "Russian", "А а");
wlist.setWord("ah", "English", "a as in another");
wlist.setWord("ah", "name", "ah");
wlist.setWord("beh", "Russian", "Б б");
wlist.setWord("beh", "English", "b as in bit");
wlist.setWord("beh", "name", "beh");
wlist.setWord("veh", "Russian", "В в");
wlist.setWord("veh", "English", "v as in vine");
wlist.setWord("veh", "name", "veh");
wlist.setWord("geh", "Russian", "Г г");
wlist.setWord("geh", "English", "g as in get");
wlist.setWord("geh", "name", "geh");
wlist.setWord("deh", "Russian", "Д д");
wlist.setWord("deh", "English", "d as in door");
wlist.setWord("deh", "name", "deh");
wlist.setWord("yeh", "Russian", "Е е");
wlist.setWord("yeh", "English", "ye as in yesterday");
wlist.setWord("yeh", "name", "yeh");
wlist.setWord("yo", "Russian", "Ё ё");
wlist.setWord("yo", "English", "yo as in yonder");
wlist.setWord("yo", "name", "yo");
wlist.setWord("zheh", "Russian", "Ж ж");
wlist.setWord("zheh", "English", "zh as in pleasure");
wlist.setWord("zheh", "name", "zheh");
wlist.setWord("zeh", "Russian", "З з");
wlist.setWord("zeh", "English", "z as in zoo");
wlist.setWord("zeh", "name", "zeh");
wlist.setWord("ee", "Russian", "И и");
wlist.setWord("ee", "English", "i as in kiss");
wlist.setWord("ee", "name", "ee");
wlist.setWord("eeshort", "Russian", "Й й");
wlist.setWord("eeshort", "English", "y as in boy");
wlist.setWord("eeshort", "name", "ee krAtkayeh");
wlist.setWord("kah", "Russian", "К к");
wlist.setWord("kah", "English", "k as in kitt");
wlist.setWord("kah", "name", "kah");
wlist.setWord("el", "Russian", "Л л");
wlist.setWord("el", "English", "l as in like");
wlist.setWord("el", "name", "el");
wlist.setWord("em", "Russian", "М м");
wlist.setWord("em", "English", "m as in milk");
wlist.setWord("em", "name", "em");
wlist.setWord("en", "Russian", "Н н");
wlist.setWord("en", "English", "n as in neat ");
wlist.setWord("en", "name", "en");
wlist.setWord("oh", "Russian", "О о");
wlist.setWord("oh", "English", "aw as in lawn");
wlist.setWord("oh", "name", "oh");
wlist.setWord("peh", "Russian", "П п");
wlist.setWord("peh", "English", "p as in poke");
wlist.setWord("peh", "name", "peh");
wlist.setWord("ehr", "Russian", "Р р");
wlist.setWord("ehr", "English", "r as in run");
wlist.setWord("ehr", "name", "ehr");
wlist.setWord("es", "Russian", "С с");
wlist.setWord("es", "English", "s as in see");
wlist.setWord("es", "name", "es");
wlist.setWord("teh", "Russian", "Т т");
wlist.setWord("teh", "English", "t as in take");
wlist.setWord("teh", "name", "teh");
wlist.setWord("oo", "Russian", "У у");
wlist.setWord("oo", "English", "oo as in pool");
wlist.setWord("oo", "name", "oo");
wlist.setWord("ef", "Russian", "Ф ф");
wlist.setWord("ef", "English", "f as in fish");
wlist.setWord("ef", "name", "ef");
wlist.setWord("khah", "Russian", "Х х");
wlist.setWord("khah", "English", "ch as in loch");
wlist.setWord("khah", "name", "khah");
wlist.setWord("tseh", "Russian", "Ц ц");
wlist.setWord("tseh", "English", "ts as in sits");
wlist.setWord("tseh", "name", "tseh");
wlist.setWord("cheh", "Russian", "Ч ч");
wlist.setWord("cheh", "English", "ch as in chair");
wlist.setWord("cheh", "name", "cheh");
wlist.setWord("sheh", "Russian", "Ш ш");
wlist.setWord("sheh", "English", "sh as in shop");
wlist.setWord("sheh", "name", "sheh");
wlist.setWord("scheh", "Russian", "Щ щ");
wlist.setWord("scheh", "English", "sh as in sheep");
wlist.setWord("scheh", "name", "scheh");
wlist.setWord("eigh", "Russian", "ы");
wlist.setWord("eigh", "English", "ei as in being");
wlist.setWord("eigh", "name", "eigh");
wlist.setWord("eh", "Russian", "Э э");
wlist.setWord("eh", "English", "e as in peg");
wlist.setWord("eh", "name", "eh");
wlist.setWord("yu", "Russian", "Ю ю");
wlist.setWord("yu", "English", "yoo as duke");
wlist.setWord("yu", "name", "yu");
wlist.setWord("ya", "Russian", "Я я");
wlist.setWord("ya", "English", "ya as in yarn");
wlist.setWord("ya", "name", "ya");
wlist.setWord("tvyordiznak", "Russian", "ъ");
wlist.setWord("tvyordiznak", "English", "hard");
wlist.setWord("tvyordiznak", "name", "tvYOrdi znak");
wlist.setWord("myakeeznak", "Russian", "ь");
wlist.setWord("myakeeznak", "English", "soft");
wlist.setWord("myakeeznak", "name", "mYAkee znak");
