langs = ["English","Swahili"];

wlist = new WordList();

wlist.setWord("AA2", "English", "And");
wlist.setWord("AA2", "Swahili", "Na");
wlist.setWord("AA3", "English", "Animals");
wlist.setWord("AA3", "Swahili", "Wanyama");
wlist.setWord("AA4", "English", "Answer");
wlist.setWord("AA4", "Swahili", "Jibu");
wlist.setWord("AA5", "English", "Ask");
wlist.setWord("AA5", "Swahili", "Uliza");
wlist.setWord("AA6", "English", "Chair");
wlist.setWord("AA6", "Swahili", "Kiti");
wlist.setWord("AA7", "English", "Coffee");
wlist.setWord("AA7", "Swahili", "Kahawa");
wlist.setWord("AA8", "English", "Come here");
wlist.setWord("AA8", "Swahili", "Njo Hapa");
wlist.setWord("AA9", "English", "Danger");
wlist.setWord("AA9", "Swahili", "Hatari");
wlist.setWord("AA10", "English", "Drink");
wlist.setWord("AA10", "Swahili", "Kunywa");
wlist.setWord("AA11", "English", "Driver");
wlist.setWord("AA11", "Swahili", "Dereva");
wlist.setWord("AA12", "English", "Eat");
wlist.setWord("AA12", "Swahili", "Kula");
wlist.setWord("AA13", "English", "Excuse me!");
wlist.setWord("AA13", "Swahili", "Samahani!");
wlist.setWord("AA14", "English", "Fish");
wlist.setWord("AA14", "Swahili", "Samaki");
wlist.setWord("AA15", "English", "Food");
wlist.setWord("AA15", "Swahili", "Chakula");
wlist.setWord("AA16", "English", "Friend");
wlist.setWord("AA16", "Swahili", "Rafiki");
wlist.setWord("AA17", "English", "Give me");
wlist.setWord("AA17", "Swahili", "Nipe");
wlist.setWord("AA18", "English", "Good");
wlist.setWord("AA18", "Swahili", "Nzuri");
wlist.setWord("AA19", "English", "Goodbye");
wlist.setWord("AA19", "Swahili", "Kwaheli");
wlist.setWord("AA20", "English", "He");
wlist.setWord("AA20", "Swahili", "Yeye");
wlist.setWord("AA21", "English", "Hello");
wlist.setWord("AA21", "Swahili", "Jambo");
wlist.setWord("AA22", "English", "Help me");
wlist.setWord("AA22", "Swahili", " please!");
wlist.setWord("AA23", "English", "How are you?-");
wlist.setWord("AA23", "Swahili", "Habari");
wlist.setWord("AA24", "English", "Hunger");
wlist.setWord("AA24", "Swahili", "Njaa");
wlist.setWord("AA25", "English", "I");
wlist.setWord("AA25", "Swahili", "Mimi");
wlist.setWord("AA26", "English", "I do not have");
wlist.setWord("AA26", "Swahili", "Sina");
wlist.setWord("AA27", "English", "I do not know");
wlist.setWord("AA27", "Swahili", "Sijui");
wlist.setWord("AA28", "English", "I love you!");
wlist.setWord("AA28", "Swahili", "Ninakupenda!");
wlist.setWord("AA29", "English", "Leopard");
wlist.setWord("AA29", "Swahili", "Chui");
wlist.setWord("AA30", "English", "Lion");
wlist.setWord("AA30", "Swahili", "Simba");
wlist.setWord("AA31", "English", "Luggage");
wlist.setWord("AA31", "Swahili", "Mizigo");
wlist.setWord("AA32", "English", "Man");
wlist.setWord("AA32", "Swahili", "Mwnamume");
wlist.setWord("AA33", "English", "Name");
wlist.setWord("AA33", "Swahili", "Jina");
wlist.setWord("AA34", "English", "No!");
wlist.setWord("AA34", "Swahili", "Hapana!");
wlist.setWord("AA35", "English", "Now");
wlist.setWord("AA35", "Swahili", "Sasa");
wlist.setWord("AA36", "English", "OK!");
wlist.setWord("AA36", "Swahili", "Sawa");
wlist.setWord("AA37", "English", "People");
wlist.setWord("AA37", "Swahili", "Watu");
wlist.setWord("AA38", "English", "Please");
wlist.setWord("AA38", "Swahili", "Tafadhali");
wlist.setWord("AA39", "English", "Quickly");
wlist.setWord("AA39", "Swahili", "Upesi");
wlist.setWord("AA40", "English", "Road");
wlist.setWord("AA40", "Swahili", "Njia");
wlist.setWord("AA41", "English", "Shop");
wlist.setWord("AA41", "Swahili", "Maduka");
wlist.setWord("AA42", "English", "Shut");
wlist.setWord("AA42", "Swahili", "Funga");
wlist.setWord("AA43", "English", "Sing");
wlist.setWord("AA43", "Swahili", "Imba");
wlist.setWord("AA44", "English", "Slowly");
wlist.setWord("AA44", "Swahili", "Plepole");
wlist.setWord("AA45", "English", "Sorry");
wlist.setWord("AA45", "Swahili", "Samahani");
wlist.setWord("AA46", "English", "Tea");
wlist.setWord("AA46", "Swahili", "Chai");
wlist.setWord("AA47", "English", "Teacher");
wlist.setWord("AA47", "Swahili", "Mwalimu");
wlist.setWord("AA48", "English", "Thank you");
wlist.setWord("AA48", "Swahili", "Asante");
wlist.setWord("AA49", "English", "There");
wlist.setWord("AA49", "Swahili", "Pale");
wlist.setWord("AA50", "English", "They");
wlist.setWord("AA50", "Swahili", "Wao");
wlist.setWord("AA51", "English", "Today");
wlist.setWord("AA51", "Swahili", "Leo");
wlist.setWord("AA52", "English", "Tomorrow");
wlist.setWord("AA52", "Swahili", "Kesho");
wlist.setWord("AA53", "English", "Tourist");
wlist.setWord("AA53", "Swahili", "Mutari");
wlist.setWord("AA54", "English", "Traveller");
wlist.setWord("AA54", "Swahili", "Msafiri");
wlist.setWord("AA55", "English", "Tree");
wlist.setWord("AA55", "Swahili", "Mti");
wlist.setWord("AA56", "English", "Village");
wlist.setWord("AA56", "Swahili", "Kijiji");
wlist.setWord("AA57", "English", "Water");
wlist.setWord("AA57", "Swahili", "Maji");
wlist.setWord("AA58", "English", "We");
wlist.setWord("AA58", "Swahili", "Sisi");
wlist.setWord("AA59", "English", "Welcome!");
wlist.setWord("AA59", "Swahili", "Karibu");
wlist.setWord("AA60", "English", "What?");
wlist.setWord("AA60", "Swahili", "Nini?");
wlist.setWord("AA61", "English", "When?");
wlist.setWord("AA61", "Swahili", "Wkatigani");
wlist.setWord("AA62", "English", "Where?");
wlist.setWord("AA62", "Swahili", "Wapi?");
wlist.setWord("AA63", "English", "Which?");
wlist.setWord("AA63", "Swahili", "Ipi?");
wlist.setWord("AA64", "English", "Write");
wlist.setWord("AA64", "Swahili", "Andika");
wlist.setWord("AA65", "English", "Yes");
wlist.setWord("AA65", "Swahili", "Ndiyo");
wlist.setWord("AA66", "English", "You");
wlist.setWord("AA66", "Swahili", "Wewe");
